RULES_CFG = {
    "K": [["K1"], ["K1", "Pel"], ["K1", "Ket"], ["K1", "K2"]],
    "K1": [["S", "P"]],
    "K2": [["Pel", "Ket"]],
    "S": [["NP"]],
    "P": [["NumP"]],
    "Pel": [["AdjP"], ["VP"]],
    "Ket": [["PP"]],
    "NP": [["Noun"], ["NumP", "NP"], ["NP", "NP"], ["NP", "PropNoun"], ["NP", "Pronoun"], 
           ["Pronoun"], ["PropNoun"], ["Adv", "NP"], ["NP", "Det"], ["NP", "AdjP"], ["NP", "Adv"]],
    "NumP": [["Num"], ["NumP", "Noun"], ["NumP", "NP", "Det"], ["NumP", "NumP"]],
    "AdjP": [["Adj"], ["AdjP", "AdjP"], ["AdjP", "Adv"], ["Adv", "AdjP"]],
    "VP": [["V"], ["VP", "NP"], ["VP", "AdjP"], ["VP", "NumP"], ["Adv", "VP"]],
    "PP": [["Prep", "NP"], ["Prep", "Det", "NP"], ["Prep", "AdjP"], ["Prep", "NumP"], ["Prep", "Adv"]],

    "PropNoun": [
        ["Aad"], ["Aang"], ["Aantaran"], ["Abhogari"], ["Adi Parwa"], 
        ["Adi Kesuma"], ["Aditya"], ["Agni"], ["Ajeg Bali"], ["Aji Kuda"], 
        ["Aji Wegig"], ["Anggara Krulut"], ["Anggara Kuningan"], 
        ["Anggara Sungsang"], ["Anggara Tambir"], ["Anantabhoga"], 
        ["Anantaboga"], ["Anoman"], ["Arjuna"], ["Arjuna Sakti"], 
        ["Arnawa"], ["Asu Bang Bungkem"], ["Asu Manak Tunggal"], 
        ["Asu Mundung"], ["Asu Ngelak"], ["Asta Brata"], ["Asta Dusta"], 
        ["Asta Kosala-Kosali"], ["Asta Musti"], ["Asta Windu"], 
        ["Astaguna"], ["Astungkara"], ["Atita"], ["Awignamastu"], 
        ["Ayu Kepel"], ["Bale Agung"], ["Bale Angklung"], ["Bale Bandung"], 
        ["Bale Banjar"], ["Bale Bengong"], ["Bale Bunder"], ["Bale Gede"], 
        ["Bale Gong"], ["Bale Kambang"], ["Bale Kembar"], ["Bale Lantang"], 
        ["Bale Majalila"], ["Bale Mandapa"], ["Bale Manguntur"], 
        ["Bale Mujur"], ["Bale Mundak"], ["Bale Murda"], ["Bale Ongkara"], 
        ["Bale Pagambuhan"], ["Bale Pamaksan"], ["Bale Paselang"], 
        ["Bale Pawedan"], ["Bale Pegat"], ["Bale Pelik"], ["Bale Piyasan"], 
        ["Bale Rum"], ["Bale Sakutus"], ["Bale Salunglung"], ["Bale Sari"], 
        ["Bale Subak"], ["Bale Sumangkirang"], ["Bale Tegeh"], 
        ["Bale Timbang"], ["Bale Wongkilas"], ["Bali"], ["Balian"], ["Balian Apun"], 
        ["Balian Manak"], ["Balian Sonteng"], ["Balian Tenung"], ["Balian Tetakson"], 
        ["Balian Usada"], ["Balian Uut"], ["Bamadewa"], ["Banaspati Raja"], 
        ["Banaspati Wong"], ["Barong"], ["Barong Akekirab"], ["Barong Kedingkling"], 
        ["Barong Ket"], ["Baruna"], ["Basuki"], ["Batu Kristal"], ["Batu Darah"], 
        ["Batu-batu"], ["Bayu"], ["Belimbing Wuluh"], ["Bendesa"], ["Benjang Pungkur"], 
        ["Besakih"], ["Betara Hyang"], ["Bhagendria"], ["Bhatara"], ["Bhuta Yadnya"], 
        ["Bima"], ["Bima Sangara"], ["Bima Krodha"], ["Bimo Kosa"], ["Binahong"], 
        ["Bintang Kudus"], ["Bintaro"], ["Bioskup"], ["Brahma"], ["Brahma Kala"], 
        ["Brahma Kokop"], ["Brahma Labuh Geni"], ["Brahma Padam"], ["Brahma Sandangan"], 
        ["Brahma Sulur"], ["Brahmacari"], ["Brahman"], ["Brahmana"], ["Braja Nembah"], 
        ["Bramara"], ["Bras"], ["Brata"], ["Brawadaan"], ["Buah Naga"], 
        ["Buaya Ngangsar"], ["Buda"], ["Buditama"], ["Buj Angga Amengku"], 
        ["Buj Angga Amerta"], ["Bujangga"], ["Bukit Sakti"],
         ["Covid 19"], ["Chikungunya"], ["Cokorda"], ["Danghyang"], 
        ["Darma Sunu"], ["Darma Duta"], ["Darma Gita"], ["Darma Lungid"], 
        ["Darma Santi"], ["Darma Sesana"], ["Darma Sunia"], ["Darma Tula"], 
        ["Darma Wacana"], ["Darma Yatra"], ["Dasa Wara"], ["Dasa Sila"], 
        ["Dasabaya"], ["Dasaksara"], ["Dasawara"]
    ],

    "Pronoun": [
        ["Aan"], ["Ane"], ["Anu"], ["Apane"], ["Asapunapi"], ["Asapunika"], 
        ["Asapuniki"], ["Ateha"], ["Awak"], ["Awake"], ["Awakne"],
        ["Bali"], ["Bapané"], ["Becicané"], ["Becicané"], ["Bedaké"], ["Benané"], 
        ["Benehné"], ["Benjangné"], ["Bibihené"], ["Bibihe"], ["Bikulé"], ["Biang"], 
        ["Biu"], ["Biuné"], ["Blaganjuré"], ["Bli"], ["Bok"], ["Bongkolné"], 
        ["Buku-bukuné"], ["Bukuné"], ["Buléné"], ["Cai"], ["Cang"], ["Ia"], ["Ipun"], 
        ["Ragané"], ["Sira"], ["Titiang"], ["Da"], ["Dane"], ["Dedek"]
    ],

    "Adv": [
        ["Abang Age"], ["Acepok"], ["Adeng-adeng"], ["Ajanian"], ["Akejep"], 
        ["Akidik"], ["Alon-alon"], ["Amonto"], ["Amunapi"], ["Amunika"], 
        ["Amuniki"], ["Anyar-anyaran"], ["Apabuin"], ["Apang"], ["Ata"], 
        ["Au-au"], ["Baa"], ["Baang"], ["Baas"], ["Baas Galih"], ["Baas Mes"], 
        ["Baem"], ["Baglug"], ["Baha"], ["Bale-bale"], ["Banban"], ["Banget"], 
        ["Bareng-bareng"], ["Barengan"], ["Bas"], ["Becat-becat"], ["Bedik-bedik"], 
        ["Benjang-benjang"], ["Biasané"], ["Buin"], ["Buin Ajahan"], ["Buin Akejep"],
        ["Busabusan"], ["Cara-cara"], ["Cenik-cenik"], ["Cerik-cerik"], 
        ["Cili-cilian"], ["Cukup"], ["Daag-diig"], ["Daah-duuh"], 
        ["Dadi-dadi"], ["Dagdag-dugdug"], ["Dangap-dangap"], ["Dauh"], 
        ["Dauh Tepat"], ["Delak-delik"], ["Demam Berdarah"]
    ],

    "Adj": [
        ["Aab"], ["Abot"], ["Abra"], ["Acreng"], ["Acum"], ["Adeng"], 
        ["Adil"], ["Aeng"], ["Ageng"], ["Agung"], ["Akas"], ["Akeh"], 
        ["Alit"], ["Aluh"], ["Alus"], ["Aman"], ["Amis"], ["Andih"], 
        ["Aneh"], ["Anget"], ["Angker"], ["Angkuh"], ["Anyar"], ["Apes"], 
        ["Apik"], ["Arang"], ["Asri"], ["Atep"], ["Atos"], ["Ayu"], 
        ["Baat"], ["Bagus"], ["Badeg"], ["Baing"], ["Baingin"], ["Bakuh"], 
        ["Baled"], ["Balok"], ["Banar"], ["Banci"], ["Bancih"], ["Bangar"], ["Banger"], 
        ["Banget"], ["Bangka"], ["Bangkak"], ["Bangke"], ["Bangkotan"], 
        ["Bangkrut"], ["Bangsal"], ["Bangsat"], ["Bangseng"], ["Bangul"], 
        ["Bantal"], ["Baru"], ["Basah"], ["Bata"], ["Bau"], ["Baut"], ["Baya"], 
        ["Bayi"], ["Bebaliha"], ["Bebangkit"], ["Bebatu"], ["Bebayuan"], 
        ["Bebencahan"], ["Bebonangan"], ["Beboreh"], ["Bebotoh"], ["Becik"], 
        ["Bedagal"], ["Bedah"], ["Bedak"], ["Bede"], ["Bedeg"], ["Bedeng"], 
        ["Bedet"], ["Bedigal"], ["Bedik"], ["Bedos"], ["Bedu"], ["Bedugul"], 
        ["Bedut"], ["Beek"], ["Beengan"], ["Begah"], ["Begak"], ["Begal"], 
        ["Begawan"], ["Begeh"], ["Begig"], ["Begug"], ["Begèr"], ["Beh"], 
        ["Behel"], ["Bejad"], ["Beji"], ["Bejigar"], ["Bejug"], ["Bek"], 
        ["Bekakak"], ["Bekasam"], ["Bekayu"], ["Beki"], ["Bekicot"], ["Bekisar"], 
        ["Beku"], ["Bekul"], ["Bekung"], ["Belabar"], ["Belah"], ["Belang"], 
        ["Belang Belut"], ["Belang Bungkem"], ["Belas"], ["Belasang"], 
        ["Belat"], ["Belatung Gada"], ["Belawa"], ["Beleg"], ["Belek"], 
        ["Belekan"], ["Belekang"], ["Beler"], ["Beli"], ["Belibar"], ["Belibed"], 
        ["Belibit"], ["Belido"], ["Belig"], ["Belimbing"], ["Beling"], 
        ["Belingan"], ["Belitbit"], ["Belog"], ["Belog Magandong"], ["Belong"], 
        ["Belukan"], ["Beluntas"], ["Belur"], ["Belus"], ["Bembangan"], 
        ["Bemo"], ["Ben"], ["Bena"], ["Benahin"], ["Benai"], ["Benal"], 
        ["Benan-benan"], ["Benang"], ["Benang Pipis"], ["Benang Sedatu"], 
        ["Benang Tridatu"], ["Benben"], ["Bencah"], ["Bencangah"], ["Benceng"], 
        ["Bencingah"], ["Bencol"], ["Bende"], ["Bendega"], ["Bendot"], ["Bendu"], 
        ["Bene"], ["Beneh"], ["Beneng"], ["Benengan"], ["Beng"], ["Bengah"], 
        ["Bengang"], ["Bengayang"], ["Bengbeng"], ["Bengek"], ["Bengel"], 
        ["Benges"], ["Bengil"], ["Bengilan"], ["Bengka"], ["Bengkang"], 
        ["Bengkel"], ["Bengking"], ["Bengkis"], ["Bengkoh"], ["Bengkol"], 
        ["Bengkones"], ["Bengkuk"], ["Bengkung"], ["Bengkut"], ["Bengong"], 
        ["Bengor"], ["Bengu"], ["Bengul"], ["Benin"], ["Benjo"], ["Bensin"], 
        ["Bentawas"], ["Bentet"], ["Benting"], ["Bentir"], ["Bentis"], 
        ["Benyad"], ["Benyah"], ["Benyeg"], ["Benyek"], ["Benyel"], ["Benyig"], 
        ["Benyut"], ["Beod"], ["Berag"], ["Berag-beragan"], ["Berang"], 
        ["Berangbang"], ["Beras"], ["Berboga"], ["Bercara"], ["Bered"], 
        ["Berek"], ["Berekan"], ["Berem"], ["Beres"], ["Berig"], ["Beringin"], 
        ["Beris"], ["Berit"], ["Bero"], ["Berong"], ["Beros"], ["Beru"], 
        ["Beruk"], ["Beruk Sileman"], ["Berung"], ["Bes"], ["Besahin"], 
        ["Besar"], ["Besbas"], ["Besbes"], ["Beseg"], ["Beseh"], ["Besek"], 
        ["Besen"], ["Beser"], ["Besi"], ["Besi Berani"], ["Besik"], 
        ["Besil"], ["Besus"], ["Bet"], ["Betah"], ["Betak"], ["Betako"], 
        ["Beteg"], ["Betek"], ["Betekan"], ["Betekan Batis"], ["Betel"], 
        ["Beten"], ["Betenan"], ["Beteng"], ["Betet"], ["Betitis"], ["Betok"], 
        ["Beton"], ["Betuk"], ["Betus"], ["Betutu"], ["Beya"], ["Biad"], 
        ["Biah-biah"], ["Biakala"], ["Biakta"], ["Biana"], ["Bianglalah"], 
        ["Biapara"], ["Biar"], ["Bias"], ["Biasa"], ["Biat"], ["Biaung"], 
        ["Bibid"], ["Bibih"], ["Bibit"], ["Bibitan"], ["Bicak"], ["Bidag"], 
        ["Bidak"], ["Bidang"], ["Bidara"], ["Bide"], ["Bidugai"], 
        ["Biduri Delima"], ["Biik"], ["Biing"], ["Bija"], ["Bijal"], ["Biji"], 
        ["Bijik"], ["Bikang"], ["Bikas"], ["Biket"], ["Biksuka"], ["Bikul"], 
        ["Bikul Malaibang Pamanggangan"], ["Bila"], ["Bilang"], ["Bilangan"], 
        ["Bilih"], ["Bina"], ["Binal"], ["Binan"], ["Bincuh"], ["Bingar"], 
        ["Bingbang"], ["Bingin"], ["Bingkil"], ["Bingkilan"], ["Bingkit"], 
        ["Bingkrut"], ["Bingung"], ["Bingut"], ["Binih"], ["Bintak"], 
        ["Bintang"], ["Bintenu"], ["Bintil"], ["Bintit"], ["Bintul"], 
        ["Bintulu"], ["Binubuk"], ["Biota"], ["Bir"], ["Biri-biri"], 
        ["Bis"], ["Bisa"], ["Bisama"], ["Biseka"], ["Biting"], ["Biu"], 
        ["Biu Batu"], ["Biu Dak"], ["Biu Gadang"], ["Biu Gancan"], 
        ["Biu Gedang Saba"], ["Biu Kat"], ["Biu Kayu Bunga"], ["Biu Ketip"], 
        ["Biu Klopok"], ["Biu Mas"], ["Biu Maselab"], ["Biu Montong"], 
        ["Biu Raja"], ["Biu Sabit"], ["Biu Sawulan"], ["Biu Susu"], 
        ["Biu Udang"], ["Biuh"], ["Biulan"], ["Biunan"], ["Biur"], ["Bius"], 
        ["Biut"], ["Biyu Kukung"], ["Blabar"], ["Blabor"], ["Blabur"], 
        ["Blacu"], ["Bladbadan"], ["Blaganjur"], ["Blagbag"], ["Blakas"], 
        ["Blalu"], ["Blanak Kesambi"], ["Blandar"], ["Blandingan"], 
        ["Blang Konyét"], ["Blangko"], ["Blangsah"], ["Blangse"], 
        ["Blangsut"], ["Blanja"], ["Blatuk"], ["Blatung"], ["Blau"], 
        ["Blauk"], ["Blayag"], ["Blayuran"], ["Blebet"], ["Blecek"], 
        ["Blegeran"], ["Blego"], ["Blegos"], ["Blejing"], ["Blekek"], 
        ["Blekok"], ["Blencot"], ["Blendo"], ["Blengbong"], ["Blenget"], 
        ["Blengih"], ["Blengker"], ["Blenguh"], ["Blenyok"], ["Blibar"], 
        ["Blibis"], ["Bligbagang"], ["Bligo"], ["Bligud"], ["Blikbuk"], 
        ["Blikur"], ["Blimbing Manis"], ["Blingbing"], ["Blinguh"], 
        ["Blitbit"], ["Bliung"], ["Blius"], ["Blodor"], ["Blokotan"], 
        ["Blolong"], ["Blongkak"], ["Blongkang"], ["Blongsong"], ["Blonyoh"], 
        ["Bloran"], ["Bluang"], ["Blubuh"], ["Bludru"], ["Blulang"], 
        ["Bluluk"], ["Blulung"], ["Blungbang"], ["Blungking"], ["Bluntas"], 
        ["Bo"], ["Bobab"], ["Bobok Sajagat"], ["Bobot"], ["Bobotan"], 
        ["Bobotang"], ["Bocok"], ["Bocokan"], ["Bocor"], ["Bodag"], 
        ["Bodo"], ["Bodri"], ["Boga"], ["Bogbog"], ["Bogem"], ["Bogol"], 
        ["Bogolan"], ["Boh"], ["Bojog"], ["Bok"], ["Bok Berit"], ["Bok Gelgel"], 
        ["Bok Sosoh"], ["Bokah"], ["Bokan"], ["Bokat"], ["Boki"], ["Boko"], 
        ["Bokongan"], ["Bokor"], ["Bokoran"], ["Bola"], ["Bolong"], ["Bolos"], 
        ["Bolu"], ["Boma"], ["Bon"], ["Bonan"], ["Boncoh"], ["Boncol"], 
        ["Bondol"], ["Bondres"], ["Boneka"], ["Bongbong"], ["Bonggan"], 
        ["Bongkah"], ["Bongkang"], ["Bongkar"], ["Bongkara"], ["Bongkek"], 
        ["Bongkeng"], ["Bongkok"], ["Bongkol"], ["Bongkol Biu"], ["Bongkos"], 
        ["Bongkot"], ["Bonglak"], ["Bongoh"], ["Bongok"], ["Bongol"], 
        ["Bongés"], ["Boni"], ["Bonjor"], ["Bonsai"], ["Bontang"], ["Bontok"], 
        ["Bonyok"], ["Bor"], ["Borang"], ["Borboran"], ["Bordir"], ["Boreh"], 
        ["Borgol"], ["Borok"], ["Boros"], ["Boros Wong"], ["Bos"], ["Bosog"], 
        ["Bosok"], ["Botol"], ["Botor"], ["Boya"], ["Boyongan"], ["Bracuk"], 
        ["Bragedegan"], ["Brahma"], ["Brahmacari"], ["Brangasan"], ["Brangbang"], 
        ["Brangkas"], ["Brangti"], ["Brarakina"], ["Brarut"], ["Brasta"], 
        ["Brawah"], ["Braya"], ["Brecek"], ["Breco"], ["Brega"], ["Bregah"], 
        ["Bregas"], ["Bregedél"], ["Bregu"], ["Brejog"], ["Brekapat"], 
        ["Brekis"], ["Breng"], ["Brengbeng"], ["Brengkes"], ["Brengos"], 
        ["Breok"], ["Brerong"], ["Bresih"], ["Brigu"], ["Briguna"], 
        ["Bringket"], ["Brokoli"], ["Bronyot"], ["Bros"], ["Brosur"], 
        ["Bruagan"], ["Bruang"], ["Bruit"], ["Brumbun"], ["Brunaha"], 
        ["Brusut"], ["Bua"], ["Buag"], ["Buah"], ["Buah-buahan"], ["Buaka"], 
        ["Buana"], ["Buang"], ["Buangit"], ["Buat"], ["Buati"], ["Buaya"], 
        ["Bubu"], ["Bubug"], ["Bubuh"], ["Bubuh Pirata"], ["Bubuk"], 
        ["Bubul"], ["Bubur Bang"], ["Bucari"], ["Bucu"], ["Budal"], 
        ["Budalang"], ["Budeg"], ["Budeng"], ["Budi"], ["Budiang"], 
        ["Buduh"], ["Bugbug"], ["Bui"], ["Buik"], ["Buit-buit"], ["Buitan"], 
        ["Bujuh"], ["Buk"], ["Buka"], ["Bukakak"], ["Bukal"], ["Bukasem"], 
        ["Bukit"], ["Bukti"], ["Buku"], ["Bukuan"], ["Bukun"], ["Bukur"], 
        ["Bulak-balik"], ["Bulakan"], ["Bulan"], ["Bulan Kerabinan"], 
        ["Bulan Pitung Dina"], ["Bulan Purnama"], ["Bulang"], ["Bule"], 
        ["Buleh"], ["Bulen"], ["Bulenan"], ["Bulih"], ["Bulih Sutra"], 
        ["Bulu"], ["Bulus"], ["Bunder"], ["Bunga"], ["Bungah"], ["Bungeng"], ["Bungkah"], 
        ["Bungkak"], ["Bungkem"], ["Bungker"], ["Bungkling"], ["Bungkul"], 
        ["Bungkung"], ["Bungkus"], ["Bungkut"], ["Bunglas"], ["Bunglon"], 
        ["Bungsil"], ["Bungut"], ["Buntar"], ["Buntas"], ["Bunteh"], ["Buntek"], 
        ["Bunter"], ["Buntil"], ["Buntilan"], ["Buntut"], ["Bunut"], 
        ["Bunut Bingin"], ["Bunut Bulu"], ["Bunut Lulub"], ["Bupati"], 
        ["Burat"], ["Burbur"], ["Bureng"], ["Burik"], ["Buron"], ["Buruh"], 
        ["Busah"], ["Busana"], ["Busana Adat"], ["Busana Kundangan"], 
        ["Busana Majenukan"], ["Busana Mamukur Atmawidana"], ["Busana Muspa"], 
        ["Busana Ngayah Ka Pura"], ["Busana Pamangku"], ["Busana Wiku Dwijati"], 
        ["Busbus"], ["Buset"], ["Busi"], ["Busul"], ["Busung"], ["Busur"], 
        ["But"], ["Buta"], ["Buta Aga"], ["Buta Ari-ari"], ["Buta Kabranan"], 
        ["Buta Kakelet Balu"], ["Buta Kala"], ["Buta Tarumab"], ["Butbut"], 
        ["Butek"], ["Buteng"], ["Butuh"], ["Buu"], ["Buug"], ["Buuk"], ["Buung"], 
        ["Buungan"], ["Buyan"], ["Buyar"], ["Buyuk"], ["Buyung"], ["Buyung Jaran"], 
        ["Buyung-buyung"], ["Bwah"], ["Caak"], ["Caak Wong"], ["Cabak"], 
        ["Cabak-cibik"], ["Cabar"], ["Cabcab"], ["Cabol"], ["Cabul"], ["Cacad"], 
        ["Cacag-cicig"], ["Cacak"], ["Cacakaran"], ["Cacalan"], ["Cacang"], 
        ["Cacapan"], ["Cacar"], ["Cacarang"], ["Cacep"], ["Cacing"], 
        ["Cacopahan"], ["Cadang"], ["Cadang Gonggang"], ["Cadel"], ["Cadik"], 
        ["Cadik Galir"], ["Cadot"], ["Cadramawa"], ["Cag-cag"], ["Cagcag"], 
        ["Cagcag-cigcig"], ["Cager"], ["Caglek"], ["Cagreng"], ["Caguah"], 
        ["Cahcah"], ["Cai"], ["Cakal"], ["Cakang"], ["Cakcak"], ["Cakep"], 
        ["Caket"], ["Cakluk"], ["Cakra"], ["Caksu"], ["Caku"], ["Cakup"], 
        ["Cakup-cakup"], ["Calcal"], ["Calekutan"], ["Calep"], ["Cali"], 
        ["Caling"], ["Caling Gajah"], ["Calo"], ["Calon"], ["Caluh"], ["Caluk"], 
        ["Calung"], ["Calung Suling"], ["Camah"], ["Camar"], ["Camat"], ["Cambeng"], 
        ["Cambra"], ["Camed"], ["Cameng"], ["Camok"], ["Campah"], ["Campang"], 
        ["Camplung"], ["Campuh"], ["Campuhan"], ["Campur"], ["Camput"], ["Canang"], 
        ["Canang Genten"], ["Canang Pangraos"], ["Canang Raka"], ["Canang Sari"], 
        ["Canda"], ["Candakan"], ["Candala"], ["Candala Sabda"], ["Candang"], 
        ["Candang Bengka"], ["Candet"], ["Candetan"], ["Candi"], ["Candi Bentar"], 
        ["Candi Kurung"], ["Candi Masuwing"], ["Candik"], ["Candik Jala"], 
        ["Candra"], ["Candra Praleka"], ["Canduk Muka"], ["Candula"], ["Candung"], 
        ["Caneg"], ["Cang"], ["Cangak"], ["Cangcang"], ["Cange"], ["Canggah"], 
        ["Canggem"], ["Cangget"], ["Canggih"], ["Canggol"], ["Canging"], 
        ["Cangkah"], ["Cangkem"], ["Cangkir"], ["Cangkling"], ["Cangklong"], 
        ["Cangklung"], ["Cangkok"], ["Cangkokah"], ["Cangkrama"], ["Cangkrim"], 
        ["Cangkring"], ["Canglak"], ["Cantaka"], ["Cantelan"], ["Canteng"], 
        ["Cantet"], ["Canteta"], ["Cantik"], ["Canting"], ["Cantok"], ["Cap"], 
        ["Cap Jempol"], ["Capah"], ["Capahan"], ["Capala"], ["Capat"], 
        ["Capatin"], ["Capatin"], ["Capcae"], ["Capil"], ["Caping"], ["Caplag"], 
        ["Caplak"], ["Capleng"], ["Caplok"], ["Caplus"], ["Capuh"], ["Capung"], 
        ["Capung Gantung"], ["Capung Gobogan"], ["Capung Klekitikan"], 
        ["Capung Kok"], ["Cara"], ["Carak"], ["Caraka"], ["Carakan"], ["Carang"], 
        ["Carangcang Kawat"], ["Caratan"], ["Carca"], ["Carcan"], ["Carik"], 
        ["Carikan"], ["Carikang"], ["Carikanga"], ["Carike"], ["Carikin"], 
        ["Carikina"], ["Carita"], ["Carma"], ["Caru"], ["Caru Be Caruk"], 
        ["Caru Dengen"], ["Caru Pangruak"], ["Carub"], ["Caruk"], ["Catet"], 
        ["Catetan"], ["Catok"], ["Catra"], ["Catri"], ["Catu"], ["Catu Meres"], 
        ["Catu Mujung"], ["Catur"], ["Catur Asrama"], ["Catur Desa"], 
        ["Catur Dewata"], ["Catur Guru"], ["Catur Kumba"], ["Catur Loka"], 
        ["Catur Muka"], ["Catur Sanak"], ["Catur Upaya Sandi"], ["Catur Wara"], 
        ["Catur Warga"], ["Catur Wangsa"], ["Caturwara"], ["Catut"], ["Catét"], 
        ["Cawan"], ["Cawang"], ["Cawet"], ["Caya"], ["Cebleng"], ["Cebur"], 
        ["Cecak"], ["Cecangkitan"], ["Cecangkriman"], ["Cecapan"], ["Cecek"], 
        ["Cecel"], ["Cecepan"], ["Cecetrung"], ["Cecimpedan"], ["Cecunduk"], 
        ["Ceda"], ["Ceda Angga"], ["Cedang"], ["Cedangin"], ["Cedar"], ["Cedik"], 
        ["Cedil"], ["Cedok"], ["Cedor"], ["Ceeng"], ["Cegah"], ["Cegceg"], 
        ["Cegem"], ["Cegeng"], ["Ceget"], ["Ceglong"], ["Ceglongan"], ["Cegur"], 
        ["Cegut"], ["Cekak"], ["Cekcek"], ["Cekel"], ["Cekelan"], ["Cekepit"], 
        ["Ceki"], ["Cekian"], ["Ceking"], ["Cekok"], ["Cekot"], ["Cekuh"], 
        ["Cekuk"], ["Celagi"], ["Celak"], ["Celana"], ["Celana Melayu"], 
        ["Celang"], ["Celap-celep"], ["Celar-celir"], ["Celcel"], ["Celeb"], 
        ["Celebingkah"], ["Celebo"], ["Celed"], ["Celeda"], ["Celedu"], 
        ["Celedu Nginyah"], ["Celek"], ["Celekang"], ["Celekutan"], 
        ["Celekutukan"], ["Celembu"], ["Celemik"], ["Celeng"], ["Celeng Alas"], 
        ["Celeng Alase"], ["Celengan"], ["Celengang"], ["Celengin"], ["Celep"], 
        ["Celepang"], ["Celepanga"], ["Celepin"], ["Celepina"], ["Celepuk"], 
        ["Celig"], ["Celih"], ["Celing"], ["Celocoh"], ["Celong"], ["Celor"], 
        ["Celuk"], ["Celuluk"], ["Celut"], ["Cemara"], ["Cematu"], ["Cemburu"], 
        ["Cemcem"], ["Cemeng"], ["Cemer"], ["Cemil"], ["Cemoh"], ["Cempaka"], 
        ["Cempaka Kuning"], ["Cempaluk"], ["Cemped"], ["Cempedan"], ["Cemplung"], 
        ["Cempurit"], ["Cemung"], ["Cen"], ["Cenana"], ["Cenanga"], ["Cendek"], 
        ["Cendekan"], ["Cendekang"], ["Cendekne"], ["Cendet"], ["Cendol"], 
        ["Cendrawasih"], ["Ceng"], ["Ceng-ceng"], ["Cengar-cengir"], ["Cengceng"], 
        ["Cengceng Ageng"], ["Cengceng Cenik"], ["Cengceng Kebyar"], 
        ["Cengceng Kopyak"], ["Cengceng Madia"], ["Cengeg"], ["Cengelan"], 
        ["Cengkang"], ["Cengkeh"], ["Cengkilik"], ["Cengkirian"], ["Cengklik"], 
        ["Cengkok"], ["Cengkrong"], ["Cengkud"], ["Cengong"], ["Cengurit"], 
        ["Cenidra"], ["Ceniga"], ["Cenik"], ["Cenik-cenik"], ["Cenikih"], ["Cenil"], 
        ["Cening"], ["Centong"], ["Centula"], ["Cepag"], ["Cepaka"], ["Cepedin"], 
        ["Cepek"], ["Ceper"], ["Cepet"], ["Cepikan"], ["Cepil"], ["Ceping"], 
        ["Ceplag"], ["Cepok"], ["Cepokang"], ["Cepol"], ["Cepong"], ["Cepuk"], 
        ["Cepung"], ["Cera"], ["Ceracap"], ["Cerah"], ["Cerai"], ["Ceraken"], 
        ["Ceraki"], ["Cerancam"], ["Ceregan"], ["Cerekcek"], ["Cerekuak"], 
        ["Cerekuwak"], ["Cereme"], ["Cererek"], ["Ceret"], ["Cerida"], ["Cerik"], 
        ["Cerik Langah"], ["Cerik-cerik"], ["Ceriritan"], ["Cerita"], ["Cerme"], 
        ["Cermin"], ["Cero"], ["Cerobo"], ["Cerok"], ["Cerongcong"], ["Ceroring"], 
        ["Cerorit"], ["Cerorot"], ["Cerucut"], ["Cerukcuk"], ["Cet"], ["Cetak"], 
        ["Cetana"], ["Ceteng"], ["Cetet"], ["Cetik"], ["Cetok"], ["Ci"], ["Cibluk"], 
        ["Cicak"], ["Cicih"], ["Cicilan"], ["Cicing"], ["Cicing Macanda"], 
        ["Cicing Medemin Jalikan"], ["Cicing Ngongkong Semal"], ["Cicing Singal"], 
        ["Cicip"], ["Cicipan"], ["Cicipin"], ["Cidra"], ["Cihna"], ["Cihnain"], 
        ["Cihnaina"], ["Cihnayang"], ["Ciing"], ["Ciit"], ["Cik"], ["Cikal"], 
        ["Cikal-cikalan"], ["Cikar"], ["Cikut"], ["Cilak"], ["Cili"], 
        ["Cili-cilian"], ["Cina"], ["Cina Majalér"], ["Cincin"], ["Cindana"], 
        ["Cingak"], ["Cingakin"], ["Cingakina"], ["Cinggur"], ["Cinging"], 
        ["Cingkrem"], ["Cinglar"], ["Cintamani"], ["Cipak"], ["Ciplakan"], 
        ["Cipta Kukila"], ["Ciri"], ["Citakan"], ["Citrakara"], ["Ciung"], 
        ["Clagi"], ["Clalongan"], ["Clana"], ["Clebongkak"], ["Cledced"], 
        ["Clegokan"], ["Clekutan"], ["Clemik"], ["Clengagan"], ["Clengis"], 
        ["Clepuk"], ["Clika"], ["Clodoh"], ["Clucuh"], ["Clurit"], ["Coak"], 
        ["Coba"], ["Cobek"], ["Coblak"], ["Coblok"], ["Coblong"], ["Cocoh"], 
        ["Cocok"], ["Cocol"], ["Cocolan"], ["Cocolang"], ["Cocolanga"], 
        ["Cocolin"], ["Cocong"], ["Cocor"], ["Codet"], ["Cogroh"], ["Cok"], 
        ["Cok Balu"], ["Cokcok"], ["Cokeh"], ["Cokeli"], ["Coklat"], ["Cokok"], 
        ["Cokor"], ["Cokot"], ["Colek"], ["Colo"], ["Coloh"], ["Colok"], 
        ["Colong"], ["Colong Papah"], ["Coma"], ["Comel"], ["Compeng"], 
        ["Compong"], ["Condong"], ["Congah"], ["Congcong"], ["Conge-conge"], 
        ["Congeh"], ["Congkak"], ["Congkeh"], ["Congklok"], ["Congkod"], 
        ["Cono"], ["Conto"], ["Contok"], ["Contreng"], ["Coong"], ["Copah"], 
        ["Copet"], ["Coples"], ["Cor"], ["Corah"], ["Corahan"], ["Corak"], 
        ["Corcor"], ["Corek"], ["Corong"], ["Cote"], ["Cotek"], ["Cotol"], 
        ["Coton"], ["Cracah"], ["Cracapan"], ["Craki"], ["Craki Keling"], 
        ["Cramah"], ["Cramcam"], ["Crawis"], ["Creceh"], ["Crekcek"], ["Creki"], 
        ["Creme"], ["Cremi"], ["Crenggah"], ["Creretin"], ["Crewet"], 
        ["Criritan"], ["Crita"], ["Crobo"], ["Crongcong"], ["Croring"], 
        ["Crorot"], ["Cruing"], ["Crukcuk"], ["Cub"], ["Cubang"], ["Cublik"], 
        ["Cubluk"], ["Cucu"], ["Cucud"], ["Cucuk"], ["Cueng"], ["Cuet"], ["Cuil"], 
        ["Cuk"], ["Cuk Cuk Dar"], ["Cuka"], ["Cukcuk"], ["Cuken"], ["Cuki"], 
        ["Cukit"], ["Cukur"], ["Cula"], ["Culalong"], ["Culig"], ["Culing"], 
        ["Culuung"], ["Cumbuana"], ["Cumpu"], ["Cundang"], ["Cundang Bayar"], 
        ["Cunding"], ["Cunduk"], ["Cungih"], ["Cungklik"], ["Cunguh"], ["Cuntaka"], 
        ["Cupak"], ["Cupar"], ["Cupek"], ["Cupik"], ["Cupit"], ["Cupu"], ["Curek"], 
        ["Curiga"], ["Curik"], ["Curing"], ["Curna"], ["Cutet"], ["Cyuta"], 
        ["Céléng Ogro"], ["Daar"], ["Daara"], ["Daat"], ["Dabdab"], ["Dacin"], 
        ["Dada"], ["Dadaaran"], ["Dadag"], ["Dadah"], ["Dadak"], ["Dadalan"], 
        ["Dadalu"], ["Dadaluman"], ["Dadalune"], ["Dadang"], ["Dadap"], 
        ["Dadap Wong"], ["Dadar"], ["Dadata"], ["Dadawuhan"], ["Dadi"], 
        ["Dadi Ati"], ["Dadi-dadi"], ["Dadia"], ["Dadiang"], ["Dadinan"], 
        ["Dadinne"], ["Dadong"], ["Dados"], ["Dados Katawan"], ["Dadosang"], 
        ["Dadu"], ["Dadua"], ["Dadung"], ["Daem"], ["Dag"], ["Daga"], ["Dagad"], 
        ["Dagang"], ["Dagangan"], ["Dagdag"], ["Dagdag-dugdug"], ["Dagel"], 
        ["Daging"], ["Dagingin"], ["Daha"], ["Dahat"], ["Daja"], ["Dakangan"], 
        ["Daken"], ["Dakep"], ["Dakepa"], ["Dakepang"], ["Dakepanga"], ["Daki"], 
        ["Dakit"], ["Daksa"], ["Daksina"], ["Daksina Yana"], ["Dalancang"], 
        ["Dalang"], ["Dalange"], ["Dalem"], ["Daleman"], ["Dalet"], ["Dalih"], 
        ["Dalil"], ["Dalit"], ["Dalu"], ["Daluman"], ["Dama"], ["Damah"], 
        ["Damala"], ["Damang"], ["Damar"], ["Damar Bron"], ["Damar Kurung"], 
        ["Damar Sentir"], ["Damar Templek"], ["Damare"], ["Dame"], ["Damel"], 
        ["Dami"], ["Damil"], ["Dampar"], ["Dampeh"], ["Damper"], ["Damping"], 
        ["Dampingin"], ["Damprat"], ["Dampuk"], ["Dampukan"], ["Damuh"], 
        ["Damuh Lengis"], ["Dana"], ["Danan"], ["Danarasa"], ["Danawa"], 
        ["Danda"], ["Dandan"], ["Dang"], ["Dang Kayangan"], ["Dangan"], 
        ["Danganan"], ["Dangdang"], ["Dangdang Angelak"], ["Dangdang Angering"], 
        ["Dangdang Sungkawa"], ["Dangdung"], ["Danggul"], ["Dangil"], ["Dangin"], 
        ["Dangkal"], ["Dangkangan"], ["Dangla"], ["Dangsah"], ["Dangsahang"], 
        ["Dangsahanga"], ["Dangsek"], ["Dangsil"], ["Dangu"], ["Dangul"], 
        ["Danta"], ["Danu"], ["Danuja"], ["Danyuh"], ["Dapak"], ["Dapang"], 
        ["Dapdap Tis"], ["Dapdapangan"], ["Dapes"], ["Dapet"], ["Dapetan"], 
        ["Dapetanga"], ["Daptar"], ["Dapur"], ["Dara"], ["Dara Kepek"], ["Darane"], 
        ["Daridra"], ["Darma"], ["Darma Sesana"], ["Darpana"], ["Darsana"], 
        ["Das"], ["Das Lemah"], ["Dasa"], ["Dasan"], ["Dasar"], ["Dasaran"], 
        ["Dasari"], ["Dasi"], ["Daslemah"], ["Datengan"], ["Datu"], ["Dauhan"], 
        ["Dauhang"], ["Dausa"], ["Dausa Gede"], ["Dausa Keling"], ["Daut"], 
        ["Dawa"], ["Dawane"], ["Dawat"], ["Daweg"], ["Dawet"], ["Dawuk"], ["Daya"], 
        ["Daya Karsa"], ["Daya Lena"], ["Dayane"], ["Dayang-dayang"], 
        ["Dayanin"], ["Dayu"], ["Dayuh"], ["Dayung"], ["Debat"], ["Dedaaran"], 
        ["Dedaletan"], ["Dedali"], ["Dedampar"], ["Dedamping"], ["Dedanga"], 
        ["Dedap"], ["Dedari"], ["Dedauhan"], ["Dedeh"], ["Dedel"], ["Dedemenan"], 
        ["Dedet"], ["Dedosan"], ["Dedudukan"], ["Dedungkian"], ["Deeng"], 
        ["Degag"], ["Degdeg"], ["Degdegan"], ["Degeng"], ["Deha"], ["Dek"], 
        ["Dekah"], ["Dekdek"], ["Dekdekan"], ["Dekem"], ["Dekes"], ["Deket"], 
        ["Dekil"], ["Dekorasi"], ["Dekung"], ["Dekungan"], ["Del"], ["Deldel"], 
        ["Deldela"], ["Deldelang"], ["Deldelanga"], ["Deleg"], ["Delek"], 
        ["Delem"], ["Delep"], ["Delik"], ["Delima"], ["Deling"], ["Delman"], 
        ["Delod"], ["Delokin"], ["Deluang"], ["Deluh"], ["Delundung"], ["Demang"], 
        ["Dembel"], ["Demdem"], ["Demek"], ["Demem"], ["Demen"], ["Demenan"], 
        ["Demenin"], ["Demerit"], ["Demih"], ["Demit"]
    ],

    "Det": [
        ["Ane"], ["Apah Krama"], ["Apang"], ["Asapunapi"], ["Asapunika"], 
        ["Asapuniki"], ["Awag Awagan"], ["Ba"], ["Ba Duwur"], ["Ba Duur"],
        ["Ban"], ["Banan"], ["Bareng"], ["Be"], ["Biang"], ["Biyu"], ["Bu"],
        ["Da"], ["Dane"], ["Das"], ["Dasa"], ["Dedek"]
    ],

    "Noun": [
        ["Aab"], ["Aag"], ["Aas"], ["Aasan"], ["Aat-aatan"], ["Aba"], 
        ["Abaang"], ["Abab"], ["Ababan"], ["Abah"], ["Abah Uma"], 
        ["Abah-abah"], ["Abang"], ["Abangan"], ["Abaong"], ["Abara"], 
        ["Abarung"], ["Abas"], ["Abasan"], ["Abedik"], ["Aben"], 
        ["Abenang"], ["Abenanga"], ["Abenat"], ["Abesbes"], ["Abesik"], 
        ["Abet"], ["Abetekan"], ["Abetekan Lelintah"], ["Abian"], 
        ["Abicara"], ["Abih"], ["Abiha"], ["Abilan"], ["Abin"], ["Abing"], 
        ["Abir"], ["Ablegag"], ["Abon"], ["Abongkos"], ["Abrésé"], 
        ["Absen"], ["Abu"], ["Abug"], ["Abuk"], ["Abuku"], ["Abulih"], 
        ["Abungkul"], ["Abut"], ["Acamplusan"], ["Acara"], ["Acarya"], 
        ["Acekel"], ["Acengkang"], ["Acep"], ["Acep-acepan"], ["Acepan"], 
        ["Aci"], ["Aci-aci"], ["Acolekan"], ["Acutak"], ["Ada"], ["Adaang"], 
        ["Adadana"], ["Adake"], ["Adan"], ["Adang"], ["Adanina"], ["Adar"], 
        ["Adas"], ["Adat"], ["Adeg"], ["Adeg Kurna"], ["Adegan"], 
        ["Adegan Tenggala"], ["Adek"], ["Adem"], ["Adenan"], ["Adengan"], 
        ["Adep"], ["Adepa"], ["Adepuk"], ["Adinya"], ["Adoh"], ["Adol"], 
        ["Adol-adolan"], ["Adola"], ["Adolang"], ["Adonan"], ["Adri"], 
        ["Adu"], ["Adua"], ["Aduh"], ["Aduk"], ["Aduk-aduk"], ["Adukang"], 
        ["Adung"], ["Adungang"], ["Adwitia"], ["Aep"], ["Aet"], 
        ["Aga Siluman"], ["Agak"], ["Agal"], ["Agama"], ["Age"], ["Agebog"], 
        ["Agel"], ["Agelung"], ["Agem"], ["Agem-ageman"], ["Agemel"], 
        ["Agen"], ["Agence"], ["Aget"], ["Agil"], ["Agol"], ["Agra"], 
        ["Agrakara"], ["Agud"], ["Aguli"], ["Agumpitan"], ["Ah"], ["Ahimsa"], 
        ["Ai"], ["Aijas"], ["Aijeng"], ["Aileh"], ["Aina"], ["Air"], 
        ["Ais"], ["Aiswaryan"], ["Ajah"], ["Ajahan"], ["Ajahin"], ["Ajak"], 
        ["Ajaka"], ["Ajakanan"], ["Ajang"], ["Ajap"], ["Ajar"], ["Ajawera"], 
        ["Ajebos"], ["Ajeg"], ["Ajegang"], ["Ajeng"], ["Ajeng-ajengan"], 
        ["Ajenga"], ["Ajengan"], ["Ajengkal"], ["Ajer"], ["Ajerih"], 
        ["Aji"], ["Ajin"], ["Ajinang"], ["Aju"], ["Ajuang"], ["Ajuanga"], 
        ["Ajum"], ["Ajum-ajuman"], ["Ajuma"], ["Ajuman"], ["Ajumandirana"], 
        ["Ajumang"], ["Ajung"], ["Akadang"], ["Akah"], ["Akah Apine"], 
        ["Akah-akahan"], ["Akal"], ["Akamarin"], ["Akandung"], ["Akara"], 
        ["Akasa"], ["Akasia"], ["Akatih"], ["Ake"], ["Akebiasan"], 
        ["Akebis"], ["Akebisan"], ["Akeciran"], ["Akedik"], ["Akehan"], 
        ["Akelan"], ["Aken"], ["Akenang"], ["Akenjang"], ["Akes"], 
        ["Aketelan"], ["Akibik"], ["Akijapan"], ["Aking"], ["Akit"], 
        ["Aklambian"], ["Aksama"], ["Aksara"], ["Aksara Swalalita"], 
        ["Aksara Wayah"], ["Aksara Wreastra"], ["Aksi"], ["Aku"], ["Akuda"], 
        ["Akueh"], ["Akupak"], ["Ala"], ["Ala Ayu"], ["Ala Ngamah-amah"], 
        ["Alab"], ["Aladang"], ["Aladanga"], ["Alah"], ["Alahang"], 
        ["Alaki-rabi"], ["Alaksa"], ["Alang"], ["Alangan"], ["Alangkat"], 
        ["Alantak"], ["Alap"], ["Alas"], ["Alase"], ["Aleban"], ["Aled"], 
        ["Alep"], ["Ali-ali"], ["Alid"], ["Alih"], ["Alih-alihan"], 
        ["Alih-basa"], ["Aliha"], ["Alihang"], ["Alihanga"], ["Alihin"], 
        ["Alihpati"], ["Alika"], ["Alikan"], ["Aling-aling"], ["Alingan"], 
        ["Alis"], ["Alis-alis"], ["Alitan"], ["Alok"], ["Aloka"], ["Alon"], 
        ["Alpaka"], ["Alpaka Guru"], ["Alpaprana"], ["Alpayusa"], ["Alu"], 
        ["Alum"], ["Alumin"], ["Alun"], ["Alun-alun"], ["Alune"], 
        ["Alus Mider"], ["Alutan"], ["Amabar Buana"], ["Amah"], 
        ["Amah-amahan"], ["Amaha"], ["Amal"], ["Amanastuti"], ["Amati Geni"], 
        ["Amati Karya"], ["Amati Lelanguan"], ["Amati Lelungan"], ["Ambah"], 
        ["Ambah-ambahan"], ["Ambahin"], ["Ambahina"], ["Ambar Sari"], 
        ["Ambara"], ["Ambaralaya"], ["Ambat"], ["Ambawang"], ["Ambe"], 
        ["Ambed"], ["Ambedang"], ["Ambedanga"], ["Ambedin"], ["Ambedina"], 
        ["Ambeg Paramarta"], ["Ambek"], ["Amben"], ["Ambena"], ["Ambengan"], 
        ["Ambet"], ["Ambil"], ["Ambin"], ["Ambres"], ["Ambu"], ["Ambuak"], 
        ["Ambuh"], ["Ambuhang"], ["Ambuhanga"], ["Ambuhin"], ["Ambuhina"], 
        ["Ambul"], ["Ambun"], ["Ambungan"], ["Ambénin"], ["Amel-amel"], 
        ["Ameng"], ["Ameng-ameng"], ["Amerah"], ["Amerta"], ["Amik-amikan"], 
        ["Amis-amisan"], ["Amla"], ["Among"], ["Among-amongan"], ["Amongken"], 
        ["Amontor"], ["Amor"], ["Ampad"], ["Ampah"], ["Ampahang"], 
        ["Ampak"], ["Ampakang"], ["Ampal"], ["Ampan"], ["Ampas"], 
        ["Ampehang"], ["Ampel Gading"], ["Ampen"], ["Ampigang"], ["Ampik"], 
        ["Amplas"], ["Amplem"], ["Amplop"], ["Ampo"], ["Ampok-ampok"], 
        ["Amprag"], ["Ampru"], ["Ampud"], ["Ampuhan"], ["Ampun"], ["Ampung"], 
        ["Ampura"], ["Ampurayang"], ["Amputan"], ["Amulet"], ["Amun"], 
        ["Amunapa"], ["Amung"], ["Amunne"], ["Ana"], ["Anagata"], ["Anak"], 
        ["Anak-anakan"], ["Anake"], ["Anaman"], ["Anamika"], ["Ananda"], 
        ["Ananda Maya"], ["Ananda Maya Kosa"], ["Ancak"], ["Ancak-ancak"], 
        ["Ancala"], ["Ancang"], ["Ancangan"], ["Anceng"], ["Anci"], 
        ["Ancih-ancihan"], ["Ancit"], ["Ancrog-ancrog"], ["Ancung"], 
        ["Ancungang"], ["Ancunganga"], ["Ancungin"], ["Ancungina"], 
        ["Ancut"], ["Anda"], ["Andang"], ["Andar"], ["Andeg"], ["Andel"], 
        ["Andel-andel"], ["Andelan"], ["Andet-andet"], ["Andong"], 
        ["Anduk"], ["Andul"], ["Andungan"], ["Andus"], ["Anehang"], 
        ["Angap-angap"], ["Angas"], ["Angayubagia"], ["Angel"], ["Angen"], 
        ["Angen-angen"], ["Anget-anget"], ["Angetang"], ["Angga"], 
        ["Angga Sarira"], ["Angga Sunya Sugana"], ["Anggada"], 
        ["Anggapan"], ["Anggara"], ["Angge"], ["Anggeh"], ["Anggen"], 
        ["Anggena"], ["Angget"], ["Anggih"], ["Anggit"], ["Anggo"], 
        ["Anggon"], ["Anggona"], ["Anggrek"], ["Anggur"], ["Angguri"], 
        ["Anggurin"], ["Anggut"], ["Anggut-anggut"], ["Angin"], 
        ["Angin Baret"], ["Angin Ngalinus"], ["Anginne"], ["Angit"], 
        ["Angka"], ["Angkabang"], ["Angkabin"], ["Angkara"], 
        ["Angkat-angkat"], ["Angkeb"], ["Angken"], ["Angkep"], ["Angkid"], 
        ["Angkih-angkih"], ["Angkihan"], ["Angkihang"], ["Angkik-angkik"], 
        ["Angkitan"], ["Angklung"], ["Angkod-angkod"], ["Angkodang"], 
        ["Angkot"], ["Angkrah"], ["Angkuk"], ["Angkul-angkul"], ["Angkus"], 
        ["Anglu"], ["Angob"], ["Angob-angoban"], ["Angoh-angoh"], 
        ["Angon"], ["Angonang"], ["Angonanga"], ["Angsana"], ["Angsangan"], 
        ["Angseg"], ["Angseg-angseg"], ["Angsel"], ["Angsuh"], ["Angsur"], 
        ["Angu"], ["Angus"], ["Anjir"], ["Anjiran"], ["Anjurina"], 
        ["Annamaya"], ["Annamaya Kosa"], ["Anom"], ["Anrawang"], ["Antah"], 
        ["Antaka"], ["Antanan"], ["Antar"], ["Antawali"], ["Ante"], 
        ["Anteg"], ["Antegang"], ["Antek-antek"], ["Antem"], ["Anten"], 
        ["Anteng"], ["Antep"], ["Anti"], ["Antiang"], ["Antiga"], 
        ["Anting-anting"], ["Antok-antok"], ["Antol"], ["Antos"], 
        ["Antosang"], ["Antu"], ["Antu Naga"], ["Antugan"], ["Antukang"], 
        ["Antukanga"], ["Antun"], ["Anumana"], ["Anungkurat"], ["Anunne"], 
        ["Anuraga"], ["Anut"], ["Anyang"], ["Anyang-anyangan"], 
        ["Anyar-anyar"], ["Anyarin"], ["Anyi"], ["Anyir"], ["Anyong-anyong"], 
        ["Anyud"], ["Anyudang"], ["Anyung"], ["Ao"], ["Aon"], ["Aor"], 
        ["Apa"], ["Apah"], ["Apake"], ["Apakpakan"], ["Apal"], ["Apanga"], 
        ["Apangalantaka"], ["Apanginangan"], ["Apanimpug"], ["Apanyakanan"], 
        ["Apap"], ["Apasang"], ["Apasua"], ["Apegelangan"], ["Apek"], 
        ["Apekik"], ["Apel"], ["Apem"], ["Apenin"], ["Apepel"], ["Api"], 
        ["Api Prakpak"], ["Api Takep"], ["Api-api"], ["Apid"], ["Apih"], 
        ["Apikanga"], ["Apikul"], ["Apil"], ["Apin"], ["Apine"], ["Apinin"], 
        ["Apinpin"], ["Apisan"], ["Apit"], ["Apit Tukad"], ["Apit-apit"], 
        ["Apitan"], ["Aplud"], ["Apokat"], ["Aprancak"], ["Apsara"], 
        ["Apti"], ["Apuh"], ["Apui"], ["Apul"], ["Apun"], ["Apus"], 
        ["Apusung"], ["Arad"], ["Arah"], ["Arah-arah"], ["Arahan"], 
        ["Arajiwa"], ["Arak"], ["Arama"], ["Aran"], ["Arania"], ["Arap"], 
        ["Aras-arasan"], ["Arat"], ["Arawinda"], ["Arda"], ["Arek"], 
        ["Arek-arek"], ["Areng"], ["Arengga"], ["Arep"], ["Arepan"], 
        ["Ares"], ["Ari"], ["Ari-ari"], ["Ariang"], ["Arimong"], 
        ["Arina"], ["Arip"], ["Aris"], ["Arit"], ["Arit-aritan"], 
        ["Arita"], ["Aritang"], ["Aritanga"], ["Arja"], ["Arjana"], 
        ["Arod"], ["Aron-aron"], ["Arsa"], ["Arta"], ["Arta Brana"], 
        ["Arti"], ["Artiang"], ["Artos"], ["Arug"], ["Aruina"], ["Arum"], 
        ["Aruna Késa"], ["Arungan"], ["Asa"], ["Asab"], ["Asagan"], 
        ["Asah"], ["Asah-asah"], ["Asal"], ["Asambekan"], ["Asangkop"], 
        ["Asania"], ["Asaraja"], ["Asasih"], ["Asat"], ["Asedengan"], 
        ["Aselid"], ["Asem"], ["Asep"], ["Asepan"], ["Aserap"], ["Asi"], 
        ["Asibak"], ["Asih"], ["Asiki"], ["Asil"], ["Asin"], ["Asing"], 
        ["Asirepan"], ["Askara"], ["Aslabsaban"], ["Asli"], ["Asliaban"], 
        ["Asok"], ["Asrama"], ["Asriepan"], ["Asta"], ["Astaba"], 
        ["Astawa"], ["Asteya"], ["Asti"], ["Asti Wedana"], ["Astika Manik"], 
        ["Astra"], ["Asua"], ["Asuba Karma"], ["Asuh"], ["Asukina"], 
        ["Asung"], ["Atag"], ["Atap"], ["Atarwya"], ["Atat"], ["Atebah"], 
        ["Ated"], ["Ategeh"], ["Ateh"], ["Atehang"], ["Atehanga"], 
        ["Atelahan"], ["Atenga"], ["Atepang"], ["Ater"], ["Ati"], 
        ["Atiban"], ["Atin"], ["Atinne"], ["Atiti"], ["Atiti Krama"], 
        ["Atiwa-tiwa"], ["Atma"], ["Atma Wedana"], ["Atoru"], ["Atrek"], 
        ["Atub"], ["Atungtung"], ["Atur"], ["Aturan"], ["Aturang"], 
        ["Aturin"], ["Atén-atén"], ["Aub"], ["Auban"], ["Aud"], ["Aukud"], 
        ["Aung"], ["Aungan"], ["Aus"], ["Awag"], ["Awai"], ["Awan"], 
        ["Awanan"], ["Awanane"], ["Awar-awar"], ["Awara"], ["Awas"], 
        ["Awasarya"], ["Awiawahara"], ["Awidia"], ["Awig-awig"], ["Awih"], 
        ["Awinan"], ["Awu"], ["Awujijiwati"], ["Aya"], ["Ayaban"], 
        ["Ayah"], ["Ayam"], ["Ayan"], ["Ayang"], ["Ayat"], ["Ayeman"], 
        ["Ayong-ayong"], ["Ayub"], ["Ayun"], ["Ayunan"], ["Ayuta"], 
        ["Baag"], ["Baag-biing"], ["Baah"], ["Baak"], ["Baan"], ["Baana"], 
        ["Baanga"], ["Baat"], ["Babad"], ["Babah"], ["Babak"], 
        ["Babak Belur"], ["Babakan"], ["Babang"], ["Babar"], ["Babasan"], 
        ["Babat"], ["Babatan"], ["Babaton"], ["Babedag"], ["Babetekan"], 
        ["Babih"], ["Babit"], ["Babita"], ["Bablanjan"], ["Bablanjanne"], 
        ["Babuan"], ["Babuang"], ["Babuk"], ["Babuten"], ["Baca"], 
        ["Bacak"], ["Bacaka"], ["Bacakan"], ["Bacakang"], ["Bacana"], 
        ["Bacin"], ["Baco"], ["Bacol"], ["Bada"], ["Badah"], ["Badaja"], 
        ["Badajanan"], ["Badak"], ["Badangin"], ["Badauh"], ["Bade"], 
        ["Badeeng"], ["Badelod"], ["Badeng"], ["Bades"], ["Badi"], 
        ["Badih"], ["Badoh"], ["Badong"], ["Badung"], ["Badungal"], 
        ["Baduur"], ["Baga"], ["Baged"], ["Bagia"], ["Bagian"], ["Bagor"], 
        ["Bah"], ["Bah Bangun"], ["Bah Bedeg"], ["Bahang"], ["Bahanga"], 
        ["Bahni"], ["Bahu"], ["Bahu Danda"], ["Bahu Mantra"], ["Bahu Pada"], 
        ["Bahu Raksa"], ["Bahu Sastra"], ["Baig"], ["Bais"], ["Baita"], 
        ["Bajag"], ["Bajang"], ["Bajang-bajang"], ["Baji"], ["Bajing"], 
        ["Bajo"], ["Bajra"], ["Baju"], ["Baju Doplang"], ["Baju Kutang"], 
        ["Baju Putra"], ["Baju Putri"], ["Bak"], ["Bakal"], ["Bakang-bakang"], 
        ["Bakat"], ["Bakbakan"], ["Baki"], ["Baksa"], ["Bakta"], ["Bakti"], 
        ["Bakung"], ["Bakungan"], ["Bal"], ["Bala"], ["Baladan"], 
        ["Balain"], ["Balan"], ["Balang"], ["Balang Kekekan"], 
        ["Balang Sangit"], ["Balange"], ["Balap"], ["Balapan"], ["Balat"], 
        ["Balbal"], ["Bale"], ["Baleman"], ["Balenging"], ["Baler"],
        ["Baleran"], ["Bales"], ["Baligi"], ["Baligrafi"], ["Balih-balihan"], 
        ["Balihin"], ["Balihina"], ["Balik"], ["Balik Sumpah"], ["Balikang"], 
        ["Balin"], ["Balongan"], ["Balu"], ["Balu Entut"], ["Balu Putung"], 
        ["Balu Rajeg"], ["Balu Remba"], ["Balu Remban"], ["Baluan"], 
        ["Baluh-baluh"], ["Balung"], ["Balung Gending"], ["Balur"], ["Balut"], 
        ["Bama"], ["Banah"], ["Banang-banang"], ["Banas"], ["Banat"], 
        ["Banatang"], ["Banbanang"], ["Banbananga"], ["Bancang"], ["Bance"], 
        ["Banceh"], ["Bancel"], ["Bancut"], ["Banda"], ["Banda Gina"], 
        ["Bandar"], ["Bandeng"], ["Bandi"], ["Bandil"], ["Banding"], 
        ["Bandingang"], ["Bandinganga"], ["Bandingin"], ["Bandingina"], 
        ["Bandrang"], ["Bandrenga"], ["Bandung"], ["Bandungang"], 
        ["Bandunganga"], ["Bandungin"], ["Bandungina"], ["Bandusa"], 
        ["Bandut"], ["Banduta"], ["Bandutang"], ["Bandutanga"], ["Baneh"], 
        ["Banen"], ["Bang"], ["Bang Bungalan"], ["Bangbang"], ["Bangen"], 
        ["Banges"], ["Bangetang"], ["Bangga"], ["Banggaang"], ["Banggaanga"], 
        ["Banggayang"], ["Banggi"], ["Banggiang"], ["Banggras"], ["Banggul"], 
        ["Bangiang"], ["Bangkah"], ["Bangkal"], ["Bangkalan"], ["Bangkarna"], 
        ["Bangkebai"], ["Bangket"], ["Bangkiang"], ["Bangkig"], ["Bangkil"], 
        ["Bangkit"], ["Bangkluk"], ["Bangkong"], ["Bangkot"], ["Bangkrak"], 
        ["Bangkruk"], ["Bangku"], ["Bangkuang"], ["Bangkuk"], ["Bangkung"], 
        ["Bangkung Manak Tunggal"], ["Bangkung-bangkung"], ["Bangladan"], 
        ["Banglah"], ["Bangle"], ["Banglong"], ["Banglor"], ["Banglot"], 
        ["Banglu"], ["Bangras"], ["Bangsa"], ["Bangsah"], ["Bangsel"], 
        ["Bangseng"], ["Bangsenga"], ["Bangsengang"], ["Bangsenganga"], 
        ["Bangsing"], ["Bangsit"], ["Bangsung"], ["Bani"], ["Banianga"], 
        ["Banjang"], ["Banjar"], ["Banjur"], ["Bantal"], ["Bantang"], 
        ["Bantang Lampit"], ["Bantar"], ["Bantas"], ["Bantat"], ["Banteh"], 
        ["Banten"], ["Banten Bubuh"], ["Banten Ketipat Kelanan"], 
        ["Banten Kojong"], ["Banten Saiban"], ["Banten Tulung"], 
        ["Banteng"], ["Bantenin"], ["Bantes"], ["Bantiran"], ["Bantug"], 
        ["Banténg Bumi Lindu"], ["Banténg Kacuman"], ["Banua"], ["Banyeh"], 
        ["Banyol"], ["Banyu"], ["Baong"], ["Baos"], ["Bapa"], ["Bapak"], 
        ["Bapang"], ["Barah"], ["Barak"], ["Barang"], ["Barang-barang"], 
        ["Bareng"], ["Bares"], ["Baret"], ["Barih"], ["Baris"], ["Barung"], 
        ["Barén"], ["Basa"], ["Basa-basa"], ["Basang"], ["Basang Kaku"], 
        ["Basawa"], ["Base"], ["Base Temisi"], ["Base Tulak"], ["Baseh"], 
        ["Baskom"], ["Basmi"], ["Basong"], ["Basta"], ["Basu"], ["Basur"], 
        ["Batabin"], ["Batak"], ["Batako"], ["Batan"], ["Batang"], ["Bataran"], 
        ["Batek"], ["Batel"], ["Bati"], ["Batis"], ["Batu"], ["Batu-batuan"], 
        ["Batuan"], ["Batun"], ["Batun Bedil"], ["Batun Salak"], 
        ["Batunin"], ["Batunina"], ["Batur"], ["Baud"], ["Baudanda"], 
        ["Bauh"], ["Baur"], ["Baus"], ["Bawak"], ["Bawang"], ["Bawi"], 
        ["Bawon"], ["Baya Kapatut"], ["Bayadan"], ["Bayah"], ["Bayem"], 
        ["Bayingan"], ["Bayuh"], ["Bayuhan"], ["Bayungan"], ["Bayur"], 
        ["Be Balung"], ["Be Guling"], ["Be Tumpek"], ["Be Uyan-uyan"], 
        ["Beb"], ["Bebai"], ["Bebakalan"], ["Bebakuhan"], ["Bebali"], 
        ["Bebalihan"], ["Bebanci"], ["Bebandungan"], ["Bebaru"], ["Bebas"], 
        ["Bebataran"], ["Bebaturan"], ["Bebaudan"], ["Bebayan"], ["Bebean"], 
        ["Bebed Sudang"], ["Bebedag"], ["Bebedogan"], ["Bebeg"], ["Bebeh"], 
        ["Bebek"], ["Bebeke"], ["Bebeki"], ["Bebel"], ["Bebenan"], 
        ["Bebeng"], ["Bebenjulan"], ["Bebesen"], ["Bebet"], ["Bebidakan"], 
        ["Bebinjat"], ["Beblakasan"], ["Beblatukan"], ["Bebokong"], 
        ["Bebolong"], ["Bebongkasan"], ["Bebontot"], ["Beborehin"], 
        ["Bebratan"], ["Bebuahan"], ["Bebuduhan"], ["Bebungkilan"], 
        ["Beburon"], ["Becatan"], ["Becek"], ["Becica"], ["Becing-becing"], 
        ["Becok"], ["Becol"], ["Becong"], ["Beda"], ["Bedbeda"], 
        ["Bedbedang"], ["Bedbedanga"], ["Bedbedin"], ["Bedbedina"], 
        ["Bedeg"], ["Bedel"], ["Bedet"], ["Bedikan"], ["Bedil"], 
        ["Bedil-bedilan"], ["Bedog"], ["Bedogol"], ["Bedugul"], ["Beduu"], 
        ["Beek"], ["Beenan"], ["Beeng"], ["Begina"], ["Begug"], ["Begèr"], 
        ["Beji"], ["Bejigar"], ["Bek"], ["Bekakak"], ["Bekayu"], 
        ["Bekbekan"], ["Bekel"], ["Bekelina"], ["Bekelne"], ["Bekicot"], 
        ["Bekin"], ["Bekisar"], ["Bekul"], ["Bekung"], ["Belahan"], 
        ["Belah-belahan"], ["Belanjaang"], ["Belas"], ["Belasa"], 
        ["Belasanga"], ["Beleng"], ["Belekang"], ["Belekanga"], ["Belianga"], 
        ["Belimbing"], ["Beling"], ["Belingan"], ["Belitbit"], ["Belog"], 
        ["Belong"], ["Belukan"], ["Beluntas"], ["Belus"], ["Bembangan"], 
        ["Bemo"], ["Ben"], ["Bena"], ["Benahin"], ["Benai"], ["Benal"], 
        ["Benan-benan"], ["Benang"], ["Benang Pipis"], ["Benang Sedatu"], 
        ["Benang Tridatu"], ["Benben"], ["Bencah"], ["Bencangah"], 
        ["Benceng"], ["Bencingah"], ["Bencol"], ["Bende"], ["Bendega"], 
        ["Bendesa"], ["Bendot"], ["Bendu"], ["Bene"], ["Beneh"], ["Beneng"], 
        ["Benengan"], ["Beng"], ["Bengah"], ["Bengang"], ["Bengayang"], 
        ["Bengbeng"], ["Bengbenga"], ["Bengek"], ["Bengel"], ["Benges"], 
        ["Bengil"], ["Bengilan"], ["Bengka"], ["Bengkang"], ["Bengkel"], 
        ["Bengking"], ["Bengkis"], ["Bengkoh"], ["Bengkol"], ["Bengkones"], 
        ["Bengkuk"], ["Bengkung"], ["Bengkut"], ["Bengong"], ["Bengor"], 
        ["Bengu"], ["Bengul"], ["Benin"], ["Benjo"], ["Bensin"], 
        ["Bentawas"], ["Bentet"], ["Benting"], ["Bentir"], ["Bentis"], 
        ["Benyad"], ["Benyah"], ["Benyahang"], ["Benyeg"], ["Benyek"], 
        ["Benyel"], ["Benyig"], ["Benyut"], ["Beod"], ["Berag-beragan"], 
        ["Berang"], ["Berangbang"], ["Beras"], ["Berboga"], ["Bercara"], 
        ["Bered"], ["Berek"], ["Berekan"], ["Berem"], ["Beres"], ["Berig"], 
        ["Beringin"], ["Beris"], ["Berit"], ["Bero"], ["Berong"], ["Beros"], 
        ["Beru"], ["Beruk"], ["Beruk Sileman"], ["Berung"], ["Bes"], 
        ["Besahin"], ["Besar"], ["Besbas"], ["Besbes"], ["Beseg"], 
        ["Beseh"], ["Besek"], ["Besen"], ["Beser"], ["Besi"], ["Besi Berani"], 
        ["Besik"], ["Besil"], ["Besus"], ["Bet"], ["Betah"], ["Betak"], 
        ["Betako"], ["Betara"], ["Betara-betari"], ["Betarane"], ["Beteg"], 
        ["Betek"], ["Betekan"], ["Betekan Batis"], ["Betel"], ["Beten"], 
        ["Betenan"], ["Beteng"], ["Betet"], ["Betitis"], ["Betok"], 
        ["Beton"], ["Betuk"], ["Betus"], ["Betutu"], ["Beya"], ["Biad"], 
        ["Biah-biah"], ["Biakala"], ["Biakta"], ["Biana"], ["Bianglalah"], 
        ["Biapara"], ["Biar"], ["Bias"], ["Biasa"], ["Biat"], ["Biaung"], 
        ["Bibid"], ["Bibih"], ["Bibit"], ["Bibitan"], ["Bicak"], ["Bidag"], 
        ["Bidak"], ["Bidang"], ["Bidara"], ["Bide"], ["Bidugai"], 
        ["Biduri Delima"], ["Biik"], ["Biing"], ["Bija"], ["Bijal"], 
        ["Biji"], ["Bijik"], ["Bikang"], ["Bikas"], ["Biket"], ["Biksuka"], 
        ["Bikul"], ["Bikul Malaibang Pamanggangan"], ["Bila"], ["Bilang"], 
        ["Bilangan"], ["Bilih"], ["Bina"], ["Binal"], ["Binan"], ["Bincuh"], 
        ["Bingar"], ["Bingbang"], ["Bingin"], ["Bingkil"], ["Bingkilan"], 
        ["Bingkit"], ["Bingkrut"], ["Bingung"], ["Bingut"], ["Binih"], 
        ["Bintak"], ["Bintang"], ["Bintenu"], ["Bintil"], ["Bintit"], 
        ["Bintul"], ["Bintulu"], ["Binubuk"], ["Biota"], ["Bir"], 
        ["Biri-biri"], ["Bis"], ["Bisa"], ["Bisaang"], ["Bisain"], 
        ["Bisakan"], ["Bisama"], ["Biseka"], ["Biting"], ["Biu"], ["Biu Batu"], 
        ["Biu Dak"], ["Biu Gadang"], ["Biu Gancan"], ["Biu Gedang Saba"], 
        ["Biu Kat"], ["Biu Kayu Bunga"], ["Biu Ketip"], ["Biu Klopok"], 
        ["Biu Mas"], ["Biu Maselab"], ["Biu Montong"], ["Biu Raja"], 
        ["Biu Sabit"], ["Biu Sawulan"], ["Biu Susu"], ["Biu Udang"], 
        ["Biuh"], ["Biulan"], ["Biunan"], ["Biur"], ["Bius"], ["Biut"], 
        ["Biyu Kukung"], ["Blabar"], ["Blabor"], ["Blabur"], ["Blacu"], 
        ["Bladbadan"], ["Blaganjur"], ["Blagbag"], ["Blakas"], ["Blalu"], 
        ["Blanak Kesambi"], ["Blandar"], ["Blandingan"], ["Blang Konyét"], 
        ["Blangko"], ["Blangsah"], ["Blangse"], ["Blangsut"], ["Blanja"], 
        ["Blatuk"], ["Blatung"], ["Blau"], ["Blauk"], ["Blayag"], 
        ["Blayuran"], ["Blebet"], ["Blecek"], ["Blegeran"], ["Blego"], 
        ["Blegos"], ["Blejing"], ["Blekek"], ["Blekok"], ["Blencot"], 
        ["Blendo"], ["Blengbong"], ["Blenget"], ["Blengih"], ["Blengker"], 
        ["Blenguh"], ["Blenyok"], ["Bli"], ["Bilibar"], ["Blibis"], 
        ["Bligbagang"], ["Bligo"], ["Bligud"], ["Blikbuk"], ["Blikur"], 
        ["Blimbing"], ["Blimbing Manis"], ["Blingbing"], ["Blinguh"], 
        ["Blitbit"], ["Bliung"], ["Blius"], ["Blodor"], ["Blokotan"], 
        ["Blolong"], ["Blongkak"], ["Blongkang"], ["Blongsong"], 
        ["Blonyoh"], ["Bloran"], ["Bluang"], ["Blubuh"], ["Bludru"], 
        ["Blulang"], ["Bluluk"], ["Blulung"], ["Blungbang"], ["Blungking"], 
        ["Bluntas"], ["Bo"], ["Bobab"], ["Bobok Sajagat"], ["Bobot"], 
        ["Bobotan"], ["Bobotang"], ["Bocok"], ["Bocokan"], ["Bocor"], 
        ["Bodag"], ["Bodo"], ["Bodri"], ["Boga"], ["Bogbog"], ["Bogbogang"], 
        ["Bogbogina"], ["Bogem"], ["Bogol"], ["Bogolan"], ["Boh"], 
        ["Bojog"], ["Bok"], ["Bok Berit"], ["Bok Gelgel"], ["Bok Sosoh"], 
        ["Bokah"], ["Bokan"], ["Bokat"], ["Bokbokina"], ["Boki"], ["Boko"], 
        ["Bokongan"], ["Bokor"], ["Bokoran"], ["Bola"], ["Bolong"], 
        ["Bolos"], ["Bolu"], ["Boma"], ["Bon"], ["Bonan"], ["Boncoh"], 
        ["Boncol"], ["Bondol"], ["Bondres"], ["Boneka"], ["Bongbong"], 
        ["Bonggan"], ["Bongkah"], ["Bongkang"], ["Bongkar"], ["Bongkara"], 
        ["Bongkek"], ["Bongkeng"], ["Bongkok"], ["Bongkol"], ["Bongkol Biu"], 
        ["Bongkos"], ["Bongkot"], ["Bonglak"], ["Bongoh"], ["Bongok"], 
        ["Bongol"], ["Bongés"], ["Boni"], ["Bonjor"], ["Bonsai"], 
        ["Bontang"], ["Bontok"], ["Bonyok"], ["Bor"], ["Borang"], 
        ["Borboran"], ["Bordir"], ["Boreh"], ["Borgol"], ["Borok"], 
        ["Boros"], ["Boros Wong"], ["Bos"], ["Bosog"], ["Bosok"], ["Botol"], 
        ["Botor"], ["Boya"], ["Boyongan"], ["Bracuk"], ["Bragedegan"], 
        ["Brahma"], ["Brahmacari"], ["Brangasan"], ["Brangbang"], 
        ["Brangkas"], ["Brangti"], ["Brarakina"], ["Brarut"], ["Brasta"], 
        ["Brawah"], ["Braya"], ["Brecek"], ["Breco"], ["Brega"], ["Bregah"], 
        ["Bregas"], ["Bregedél"], ["Bregu"], ["Brejog"], ["Brekapat"], 
        ["Brekis"], ["Breng"], ["Brengbeng"], ["Brengkes"], ["Brengos"], 
        ["Breok"], ["Brerong"], ["Bresih"], ["Brigu"], ["Briguna"], 
        ["Bringket"], ["Brokoli"], ["Bronyot"], ["Bros"], ["Brosur"], 
        ["Bruagan"], ["Bruang"], ["Bruit"], ["Brumbun"], ["Brunaha"], 
        ["Brusut"], ["Bua"], ["Buag"], ["Buah"], ["Buah-buahan"], ["Buaka"], 
        ["Buana"], ["Buang"], ["Buangit"], ["Buat"], ["Buati"], ["Buaya"], 
        ["Bubu"], ["Bubug"], ["Bubuh"], ["Bubuh Pirata"], ["Bubuk"], 
        ["Bubul"], ["Bubur Bang"], ["Bucari"], ["Bucu"], ["Budal"], 
        ["Budalang"], ["Budalanga"], ["Budeg"], ["Budeng"], ["Budi"], 
        ["Budiang"], ["Budianga"], ["Buduh"], ["Bugbug"], ["Bui"], ["Buik"], 
        ["Buin"], ["Buin Manine"], ["Buina"], ["Buit-buit"], ["Buitan"], 
        ["Bujuh"], ["Buk"], ["Buka"], ["Bukakak"], ["Bukal"], ["Bukasem"], 
        ["Bukit"], ["Bukti"], ["Buku"], ["Bukuan"], ["Bukun"], ["Bukur"], 
        ["Bulak-balik"], ["Bulakan"], ["Bulan"], ["Bulan Kerabinan"], 
        ["Bulan Pitung Dina"], ["Bulan Purnama"], ["Bulang"], ["Bule"], 
        ["Buleh"], ["Bulen"], ["Bulenan"], ["Bulih"], ["Bulih Sutra"], 
        ["Bulu"], ["Bulu Mata"], ["Bulu Padi"], ["Bulu-bulu"], ["Buluan"], ["Bulung"], 
        ["Bulung Jaja"], ["Bulusan"], ["Bun"], ["Bun Swit"], ["Bun-bunan"], 
        ["Buncal"], ["Buncing"], ["Buncis"], ["Buncul"], ["Bunderan"], ["Bunga"], 
        ["Bunga Bintang"], ["Bunga Kap"], ["Bungan Tuwung"], ["Bungbung"], 
        ["Bungbung Barangan"], ["Bungbung Gebyog"], ["Bungbung Kantilan"], 
        ["Bungbung Undir"], ["Bungkah"], ["Bungkak Nyinying"], ["Bungkerang"], 
        ["Bungkeranga"], ["Bungkil"], ["Bungkung Jinar"], ["Bungkung Mas"], 
        ["Bungkung Pendok"], ["Bungkung Selaka"], ["Bungkung Tambah"], 
        ["Bungkusan"], ["Bunuh"], ["Bunut"], ["Bunut Bingin"], ["Bunut Bulu"], 
        ["Bunut Lulub"], ["Bupati"], ["Buruh"], ["Busana"], ["Busana Adat"], 
        ["Busana Kundangan"], ["Busana Majenukan"], 
        ["Busana Mamukur Atmawidana"], ["Busana Muspa"], ["Busana Ngayah Ka Pura"], 
        ["Busana Pamangku"], ["Busana Wiku Dwijati"], ["Buta Aga"], 
        ["Buta Ari-ari"], ["Buta Kabranan"], ["Buta Kakelet Balu"], ["Buta Kala"], 
        ["Buta Tarumab"], ["Buyung Jaran"], ["Cacah Jiwa"], ["Calonarang"], 
        ["Canang Genten"], ["Canang Pangraos"], ["Canang Raka"], ["Canang Sari"], 
        ["Candala Sabda"], ["Candang Bengka"], ["Candi Bentar"], ["Candi Kurung"], 
        ["Candi Masuwing"], ["Candik Jala"], ["Candra Praleka"], ["Canduk Muka"], 
        ["Catur Asrama"], ["Catur Desa"], ["Catur Dewata"], ["Catur Guru"], 
        ["Catur Kumba"], ["Catur Loka"], ["Catur Muka"], ["Catur Sanak"], 
        ["Catur Upaya Sandi"], ["Catur Wara"], ["Catur Warga"], ["Catur Wangsa"], 
        ["Caturwara"], ["Célèng Ogro"], ["Dang Kayangan"], ["Dangdang Angelak"], 
        ["Dangdang Angering"], ["Dangdang Sungkawa"], ["Dapur"], ["Darma"], 
        ["Darma Sesana"], ["Das Lemah"], ["Dasa Wara"], ["Dasa Sila"], 
        ["Dasabaya"], ["Dasaksara"], ["Dasawara"], ["Daslemah"], ["Daya Karsa"], 
        ["Daya Lena"]
    ],

    "Num": [
        ["Abesik"], ["Abungkul"], ["Acepok"], ["Adiri"], ["Akatih"], 
        ["Aketeng"], ["Aketi"], ["Alaksa"], ["Asiki"], ["Atenga"], 
        ["Atiban"], ["Aukud"], ["Baang"], ["Badasa"], ["Badom"], ["Besik"],
        ["Badom"], ["Badasa"], ["Badasa"], ["Banang"], ["Bance"], ["Bancang"], 
        ["Banggi"], ["Bangkah"], ["Bangkal"], ["Bangkalan"], ["Bangke"], 
        ["Bangket"], ["Bangkiang"], ["Bangkong"], ["Bangkot"], ["Bangku"], 
        ["Bangkuang"], ["Bangsal"], ["Bangsel"], ["Bangseng"], ["Bangsunga"], 
        ["Banjang"], ["Banjur"], ["Bantal"], ["Bantang"], ["Bantar"], 
        ["Bantas"], ["Bantat"], ["Banteh"], ["Banten"], ["Banteng"], 
        ["Banyu"], ["Baong"], ["Bapa"], ["Bapak"], ["Barang"], ["Bareng"], 
        ["Bares"], ["Baret"], ["Barih"], ["Baris"], ["Barong"], ["Barung"], 
        ["Bas"], ["Basa"], ["Basang"], ["Base"], ["Baseh"], ["Baskom"], 
        ["Basmi"], ["Basong"], ["Basta"], ["Basu"], ["Basur"], ["Bata"], 
        ["Batak"], ["Batako"], ["Batan"], ["Batang"], ["Batek"], ["Batel"], 
        ["Bati"], ["Batis"], ["Batu"], ["Batun"], ["Batur"], ["Bau"], 
        ["Baud"], ["Baudanda"], ["Bauh"], ["Baur"], ["Baus"], ["Baut"], 
        ["Bawak"], ["Bawang"], ["Bawi"], ["Bawon"], ["Baya"], ["Bayadan"], 
        ["Bayah"], ["Bayem"], ["Bayingan"], ["Bayu"], ["Bayuh"], ["Bayuhan"], 
        ["Bayungan"], ["Bayur"], ["Be"], ["Be Balung"], ["Be Guling"], 
        ["Be Tumpek"], ["Be Uyan-uyan"], ["Beb"], ["Bebai"], ["Bebakalan"], 
        ["Bebakuhan"], ["Bebali"], ["Bebalihan"], ["Bebanci"], 
        ["Bebandungan"], ["Bebangkit"], ["Bebaru"], ["Bebas"], ["Bebataran"], 
        ["Bebaturan"], ["Bebaudan"], ["Bebayan"], ["Bebean"], ["Bebed Sudang"], 
        ["Bebedag"], ["Bebedogan"], ["Bebeg"], ["Bebeh"], ["Bebek"], 
        ["Bebeke"], ["Bebeki"], ["Bebel"], ["Bebenan"], ["Bebeng"], 
        ["Bebenjulan"], ["Bebesen"], ["Bebet"], ["Bebidakan"], ["Bebinjat"], 
        ["Beblakasan"], ["Beblatukan"], ["Bebokong"], ["Bebolong"], 
        ["Bebonangan"], ["Bebongkasan"], ["Bebontot"], ["Beboreh"], 
        ["Beborehin"], ["Bebotoh"], ["Bebratan"], ["Bebuahan"], 
        ["Bebuduhan"], ["Bebungkilan"], ["Beburon"], ["Becat"], ["Becatan"], 
        ["Becek"], ["Becica"], ["Becicane"], ["Becik"], ["Becing-becing"], 
        ["Becok"], ["Becol"], ["Becong"], ["Beda"], ["Bedagal"], ["Bedah"], 
        ["Bedak"], ["Bedake"], ["Bedawang"], ["Bedbed"], ["Bedbeda"], 
        ["Bedbedang"], ["Bedbedanga"], ["Bedbedin"], ["Bedbedina"], ["Bede"], 
        ["Bedeg"], ["Bedel"], ["Bedeng"], ["Bedet"], ["Bedigal"], ["Bedik"], 
        ["Bedik-bedik"], ["Bedik-bedikin"], ["Bedikan"], ["Bedil"], 
        ["Bedil-bedilan"], ["Bedog"], ["Bedogol"], ["Bedos"], ["Bedu"], 
        ["Beduda"], ["Bedugul"], ["Bedut"], ["Beduu"], ["Beek"], ["Beenan"], 
        ["Beeng"], ["Begah"], ["Begak"], ["Begal"], ["Begawan"], ["Begbeg"], 
        ["Begeh"], ["Begig"], ["Begina"], ["Begug"], ["Begèr"], ["Beh"], 
        ["Behel"], ["Bejad"], ["Beji"], ["Bejigar"], ["Bejug"], ["Bek"], 
        ["Bekakak"], ["Bekasam"], ["Bekayu"], ["Bekbekan"], ["Bekel"], 
        ["Bekelina"], ["Bekelne"], ["Beki"], ["Bekicot"], ["Bekin"], 
        ["Bekisar"], ["Beku"], ["Bekul"], ["Bekung"], ["Belabar"], 
        ["Belah"], ["Belah-belahan"], ["Belahan"], ["Belang"], 
        ["Belang Belut"], ["Belang Bungkem"], ["Belanjaang"], ["Belas"], 
        ["Belasa"], ["Belasang"], ["Belasanga"], ["Belat"], ["Belatung Gada"], 
        ["Belawa"], ["Belayuran"], ["Beleg"], ["Belek"], ["Belekan"], 
        ["Belekang"], ["Belekanga"], ["Beleng"], ["Beler"], ["Beli"], 
        ["Belianga"], ["Belibar"], ["Belibed"], ["Belibit"], ["Belido"], 
        ["Belig"], ["Belimbing"], ["Belimbing Wuluh"], ["Beling"], 
        ["Belingan"], ["Belitbit"], ["Belog"], ["Belog Magandong"], 
        ["Belong"], ["Belukan"], ["Beluntas"], ["Belur"], ["Belus"], 
        ["Bembangan"], ["Bemo"], ["Ben"], ["Bena"], ["Benahin"], ["Benai"], 
        ["Benal"], ["Benan-benan"], ["Benane"], ["Benang"], ["Benang Pipis"], 
        ["Benang Sedatu"], ["Benang Tridatu"], ["Benangne"], ["Benben"], 
        ["Bencah"], ["Bencangah"], ["Benceng"], ["Bencingah"], ["Bencol"], 
        ["Bende"], ["Bendega"], ["Bendesa"], ["Bendot"], ["Bendu"], ["Bene"], 
        ["Beneh"], ["Benehné"], ["Beneng"], ["Benengan"], ["Beng"], ["Bengah"], 
        ["Bengang"], ["Bengayang"], ["Bengbeng"], ["Bengbenga"], ["Bengek"], 
        ["Bengel"], ["Benges"], ["Bengil"], ["Bengilan"], ["Bengka"], 
        ["Bengkang"], ["Bengkel"], ["Bengking"], ["Bengkis"], ["Bengkoh"], 
        ["Bengkol"], ["Bengkones"], ["Bengkuk"], ["Bengkung"], ["Bengkut"], 
        ["Bengong"], ["Bengor"], ["Bengu"], ["Bengul"], ["Benin"], 
        ["Benjang"], ["Benjang Pungkur"], ["Benjang-benjang"], ["Benjangne"], 
        ["Benjo"], ["Bensin"], ["Bentawas"], ["Bentet"], ["Benting"], 
        ["Bentir"], ["Bentis"], ["Benyad"], ["Benyah"], ["Benyahang"], 
        ["Benyeg"], ["Benyek"], ["Benyel"], ["Benyig"], ["Benyut"], ["Beod"], 
        ["Berag"], ["Berag-beragan"], ["Berang"], ["Berangbang"], ["Beras"], 
        ["Berboga"], ["Bercara"], ["Bered"], ["Berek"], ["Berekan"], ["Berem"], 
        ["Beres"], ["Berig"], ["Beringin"], ["Beris"], ["Berit"], ["Bero"], 
        ["Berong"], ["Beros"], ["Beru"], ["Beruk"], ["Beruk Sileman"], 
        ["Berung"], ["Bes"], ["Besahin"], ["Besakih"], ["Besar"], ["Besbas"], 
        ["Besbes"], ["Beseg"], ["Beseh"], ["Besek"], ["Besen"], ["Beser"], 
        ["Besi"], ["Besi Berani"], ["Besik"], ["Besil"], ["Besus"], ["Bet"], 
        ["Betah"], ["Betak"], ["Betako"], ["Betara"], ["Betara Hyang"], 
        ["Betara-betari"], ["Betarane"], ["Beteg"], ["Betek"], ["Betekan"], 
        ["Betekan Batis"], ["Betel"], ["Beten"], ["Betenan"], ["Beteng"], 
        ["Betet"], ["Betitis"], ["Betok"], ["Beton"], ["Betuk"], ["Betus"], 
        ["Betutu"], ["Beya"], ["Bhagendria"], ["Bhatara"], ["Bhur"], 
        ["Bhuta Yadnya"], ["Biad"], ["Biah-biah"], ["Biakala"], ["Biakta"], 
        ["Biana"], ["Biang"], ["Bianglalah"], ["Biapara"], ["Biar"], ["Bias"], 
        ["Biasa"], ["Biasane"], ["Biat"], ["Biaung"], ["Bibid"], ["Bibih"], 
        ["Bibihe"], ["Bibihne"], ["Bibit"], ["Bibitan"], ["Bicak"], ["Bidag"], 
        ["Bidak"], ["Bidang"], ["Bidara"], ["Bide"], ["Bidugai"], 
        ["Biduri Delima"], ["Biik"], ["Biing"], ["Bija"], ["Bijal"], ["Biji"], 
        ["Bijik"], ["Bikang"], ["Bikas"], ["Biket"], ["Biksuka"], ["Bikul"], 
        ["Bikul Malaibang Pamanggangan"], ["Bikule"], ["Bila"], ["Bilang"], 
        ["Bilangan"], ["Bilih"], ["Bima"], ["Bima Sangara"], ["Bima Krodha"], 
        ["Bimo Kosa"], ["Bina"], ["Binahong"], ["Binal"], ["Binan"], 
        ["Bincuh"], ["Bingar"], ["Bingbang"], ["Bingin"], ["Bingkil"], 
        ["Bingkilan"], ["Bingkit"], ["Bingkrut"], ["Bingung"], ["Bingut"], 
        ["Binih"], ["Bintak"], ["Bintang"], ["Bintang Kudus"], ["Bintaro"], 
        ["Bintenu"], ["Bintil"], ["Bintit"], ["Bintul"], ["Bintulu"], 
        ["Binubuk"], ["Bioskup"], ["Biota"], ["Bir"], ["Biri-biri"], ["Bis"], 
        ["Bisa"], ["Bisaang"], ["Bisain"], ["Bisakan"], ["Bisama"], 
        ["Biseka"], ["Biting"], ["Biu"], ["Biu Batu"], ["Biu Dak"], 
        ["Biu Gadang"], ["Biu Gancan"], ["Biu Gedang Saba"], ["Biu Kat"], 
        ["Biu Kayu Bunga"], ["Biu Ketip"], ["Biu Klopok"], ["Biu Mas"], 
        ["Biu Maselab"], ["Biu Montong"], ["Biu Raja"], ["Biu Sabit"], 
        ["Biu Sawulan"], ["Biu Susu"], ["Biu Udang"], ["Biuh"], ["Biulan"], 
        ["Biunan"], ["Biune"], ["Biur"], ["Bius"], ["Biut"], ["Biyu Kukung"], 
        ["Blabar"], ["Blabaran"], ["Blabor"], ["Blabur"], ["Blacu"], 
        ["Bladbadan"], ["Blaganjur"], ["Blaganjure"], ["Blagbag"], ["Blakas"], 
        ["Blalu"], ["Blanak Kesambi"], ["Blandar"], ["Blandingan"], 
        ["Blang Konyét"], ["Blangko"], ["Blangsah"], ["Blangse"], 
        ["Blangsut"], ["Blanja"], ["Blatuk"], ["Blatung"], ["Blau"], 
        ["Blauk"], ["Blayag"], ["Blayuran"], ["Blebet"], ["Blecek"], 
        ["Blegeran"], ["Blego"], ["Blegos"], ["Blejing"], ["Blekek"], 
        ["Blekok"], ["Blencot"], ["Blendo"], ["Blengbong"], ["Blenget"], 
        ["Blengih"], ["Blengker"], ["Blenguh"], ["Blenyok"], ["Bli"], 
        ["Blibar"], ["Blibis"], ["Bligbagang"], ["Bligo"], ["Bligud"], 
        ["Blikbuk"], ["Blikur"], ["Blimbing"], ["Blimbing Manis"], 
        ["Blingbing"], ["Blinguh"], ["Blitbit"], ["Bliung"], ["Blius"], 
        ["Blodor"], ["Blokotan"], ["Blolong"], ["Blongkak"], ["Blongkang"], 
        ["Blongsong"], ["Blonyoh"], ["Bloran"], ["Bluang"], ["Blubuh"], 
        ["Bludru"], ["Blulang"], ["Bluluk"], ["Blulung"], ["Blungbang"], 
        ["Blungking"], ["Bluntas"], ["Bo"], ["Bobab"], ["Bobok Sajagat"], 
        ["Bobot"], ["Bobotan"], ["Bobotang"], ["Bocok"], ["Bocokan"], 
        ["Bocor"], ["Bodag"], ["Bodo"], ["Bodri"], ["Boga"], ["Bogbog"], 
        ["Bogbogang"], ["Bogbogina"], ["Bogem"], ["Bogol"], ["Bogolan"], 
        ["Boh"], ["Bojog"], ["Bok"], ["Bok Berit"], ["Bok Gelgel"], 
        ["Bok Sosoh"], ["Bokah"], ["Bokan"], ["Bokat"], ["Bokbokina"], 
        ["Boki"], ["Boko"], ["Bokongan"], ["Bokor"], ["Bokoran"], ["Bola"], 
        ["Bolong"], ["Bolos"], ["Bolu"], ["Boma"], ["Bon"], ["Bonan"], 
        ["Boncoh"], ["Boncol"], ["Bondol"], ["Bondres"], ["Boneka"], 
        ["Bongbong"], ["Bonggan"], ["Bongkah"], ["Bongkang"], ["Bongkar"], 
        ["Bongkara"], ["Bongkek"], ["Bongkeng"], ["Bongkok"], ["Bongkol"], 
        ["Bongkol Biu"], ["Bongkolne"], ["Bongkos"], ["Bongkot"], 
        ["Bonglak"], ["Bongoh"], ["Bongok"], ["Bongol"], ["Bongés"], 
        ["Boni"], ["Bonjor"], ["Bonsai"], ["Bontang"], ["Bontok"], 
        ["Bonyok"], ["Bor"], ["Borang"], ["Borboran"], ["Bordir"], ["Boreh"], 
        ["Borgol"], ["Borok"], ["Boros"], ["Boros Wong"], ["Bos"], ["Bosog"], 
        ["Bosok"], ["Botol"], ["Botor"], ["Boya"], ["Boyongan"], ["Bracuk"], 
        ["Bragedegan"], ["Brahma"], ["Brahma Kala"], ["Brahma Kokop"], 
        ["Brahma Labuh Geni"], ["Brahma Padam"], ["Brahma Sandangan"], 
        ["Brahma Sulur"], ["Brahmacari"], ["Brahman"], ["Brahmana"], 
        ["Braja Nembah"], ["Bramara"], ["Brana"], ["Brangasan"], ["Brangbang"], 
        ["Brangkas"], ["Brangti"], ["Brarakina"], ["Brarut"], ["Brasta"], 
        ["Brata"], ["Brawadaan"], ["Brawah"], ["Braya"], ["Brecek"], 
        ["Breco"], ["Brega"], ["Bregah"], ["Bregas"], ["Bregedél"], 
        ["Bregu"], ["Brejog"], ["Brekapat"], ["Brekis"], ["Breng"], 
        ["Brengbeng"], ["Brengkes"], ["Brengos"], ["Breok"], ["Brerong"], 
        ["Bresih"], ["Bresihin"], ["Brigu"], ["Briguna"], ["Bringket"], 
        ["Brokoli"], ["Bronyot"], ["Bros"], ["Brosur"], ["Bruagan"], 
        ["Bruang"], ["Bruit"], ["Brumbun"], ["Brunaha"], ["Brusut"], ["Bua"], 
        ["Buag"], ["Buah"], ["Buah Naga"], ["Buah-buahan"], ["Buaka"], 
        ["Buana"], ["Buang"], ["Buangit"], ["Buat"], ["Buati"], ["Buaya"], 
        ["Buaya Ngangsar"], ["Bubu"], ["Bubug"], ["Bubuh"], ["Bubuh Pirata"], 
        ["Bubuk"], ["Bubul"], ["Bubur Bang"], ["Bucari"], ["Bucu"], ["Buda"], 
        ["Budal"], ["Budalang"], ["Budalanga"], ["Budeg"], ["Budeng"], 
        ["Budi"], ["Budiang"], ["Budianga"], ["Buditama"], ["Buduh"], 
        ["Bugbug"], ["Bui"], ["Buik"], ["Buin"], ["Buin Manine"], 
        ["Buin Ajahan"], ["Buin Akejep"], ["Buina"], ["Buit-buit"], 
        ["Buitan"], ["Buj Angga Amengku"], ["Buj Angga Amerta"], ["Bujangga"], 
        ["Bujuh"], ["Buk"], ["Buka"], ["Bukakak"], ["Bukal"], ["Bukasem"], 
        ["Bukit"], ["Bukit Sakti"], ["Bukti"], ["Buku"], ["Buku-bukune"], 
        ["Bukuan"], ["Bukun"], ["Bukune"], ["Bukur"], ["Bulak-balik"], 
        ["Bulakan"], ["Bulan"], ["Bulan Kerabinan"], ["Bulan Pitung Dina"], 
        ["Bulan Purnama"], ["Bulang"], ["Bule"], ["Buleh"], ["Bulen"], 
        ["Bulenan"], ["Bulene"], ["Bulih"], ["Bulih Sutra"], ["Bulu"],
        ["Cacah"], ["Cacah Jiwa"], ["Dasa"], ["Dadua"]
    ],

    "Verb": [
        ["Aba"], ["Abaang"], ["Acep"], ["Ada"], ["Adep"], ["Ajah"], 
        ["Ajak"], ["Ajeng"], ["Aksi"], ["Alah"], ["Alap"], ["Alih"], 
        ["Ambil"], ["Among"], ["Ampura"], ["Ana"], ["Ancang"], ["Andel"], 
        ["Angel"], ["Angen"], ["Angge"], ["Anggon"], ["Antos"], ["Antuk"], 
        ["Anut"], ["Anyang"], ["Anyir"], ["Anyud"], ["Aon"], ["Aor"], 
        ["Apal"], ["Apit"], ["Arak"], ["Arek"], ["Arep"], ["Arit"], 
        ["Arug"], ["Asah"], ["Asih"], ["Asing"], ["Asu"], ["Asung"], 
        ["Atur"], ["Aukud"], ["Aung"], ["Awag"], ["Ayun"], ["Baang"], 
        ["Babat"], ["Baca"], ["Badeg"], ["Bagia"], ["Bagus"], ["Bah"], 
        ["Bajang"], ["Bakal"], ["Bakti"], ["Bala"], ["Balap"], ["Baler"],
        ["Baleran"], ["Bales"], ["Balih"], ["Balihin"], ["Balik"], 
        ["Balikang"], ["Balin"], ["Balok"], ["Balon"], ["Balung"], ["Balur"], 
        ["Balut"], ["Bama"], ["Ban"], ["Banah"], ["Banang"], ["Banar"], 
        ["Banas"], ["Banat"], ["Banatang"], ["Banban"], ["Banbanang"], 
        ["Bancang"], ["Bance"], ["Banceh"], ["Bancel"], ["Banci"], 
        ["Bancih"], ["Bancingah"], ["Bancuk"], ["Bancut"], ["Banda"], 
        ["Bandar"], ["Bandeng"], ["Bandi"], ["Bandil"], ["Banding"], 
        ["Bandingang"], ["Bandingin"], ["Bandrang"], ["Bandrenga"], 
        ["Bandung"], ["Bandungang"], ["Bandungin"], ["Bandusa"], ["Bandut"], 
        ["Banduta"], ["Bandutang"], ["Baneh"], ["Banen"], ["Bang"], 
        ["Bangar"], ["Bangbang"], ["Bangen"], ["Banger"], ["Banges"], 
        ["Banget"], ["Bangetang"], ["Bangga"], ["Banggaang"], ["Banggayang"], 
        ["Banggi"], ["Banggiang"], ["Banggras"], ["Banggul"], ["Bangiang"], 
        ["Bangka"], ["Bangkah"], ["Bangkak"], ["Bangkal"], ["Bangkalan"], 
        ["Bangkarna"], ["Bangke"], ["Bangkebai"], ["Bangket"], ["Bangkiang"], 
        ["Bangkig"], ["Bangkil"], ["Bangkit"], ["Bangkluk"], ["Bangkong"], 
        ["Bangkot"], ["Bangkotan"], ["Bangkrak"], ["Bangkruk"], 
        ["Bangkrut"], ["Bangku"], ["Bangkuang"], ["Bangkuk"], ["Bangkung"], 
        ["Bangkung Manak Tunggal"], ["Bangkung-bangkung"], ["Bangladan"], 
        ["Banglah"], ["Bangle"], ["Banglong"], ["Banglor"], ["Banglot"], 
        ["Banglu"], ["Bangras"], ["Bangsa"], ["Bangsah"], ["Bangsal"], 
        ["Bangsat"], ["Bangsel"], ["Bangseng"], ["Bangsenga"], 
        ["Bangsengang"], ["Bangsing"], ["Bangsit"], ["Bangsung"], ["Bangul"], 
        ["Bangun"], ["Bani"], ["Banianga"], ["Banjang"], ["Banjar"], 
        ["Banjur"], ["Bantal"], ["Bantang"], ["Bantang Lampit"], ["Bantar"], 
        ["Bantas"], ["Bantat"], ["Banteh"], ["Banten"], ["Banten Bubuh"], 
        ["Banten Ketipat Kelanan"], ["Banten Kojong"], ["Banten Saiban"], 
        ["Banten Tulung"], ["Banteng"], ["Bantenin"], ["Bantes"], 
        ["Bantiran"], ["Bantug"], ["Banténg Bumi Lindu"], ["Banténg Kacuman"], 
        ["Banua"], ["Banyeh"], ["Banyol"], ["Banyu"], ["Baong"], ["Baos"], 
        ["Bapa"], ["Bapak"], ["Bapane"], ["Bapang"], ["Barah"], ["Barak"], 
        ["Barang"], ["Barang-barang"], ["Bareng"], ["Bareng-bareng"], 
        ["Barengan"], ["Barengang"], ["Bares"], ["Baret"], ["Barih"], 
        ["Baris"], ["Barong"], ["Barong Akekirab"], ["Barong Kedingkling"], 
        ["Barong Ket"], ["Baru"], ["Baruna"], ["Barung"], ["Barén"], ["Bas"], 
        ["Basa"], ["Basa-basa"], ["Basah"], ["Basang"], ["Basang Kaku"], 
        ["Basawa"], ["Base"], ["Base Temisi"], ["Base Tulak"], ["Baseh"], 
        ["Baskom"], ["Basmi"], ["Basong"], ["Basta"], ["Basu"], ["Basuki"], 
        ["Basur"], ["Bata"], ["Batabin"], ["Batak"], ["Batako"], ["Batan"], 
        ["Batang"], ["Bataran"], ["Batek"], ["Batel"], ["Bati"], ["Batis"], 
        ["Batisne"], ["Batu"], ["Batu Darah"], ["Batu Kristal"], 
        ["Batu-batu"], ["Batu-batuan"], ["Batuan"], ["Batun"], 
        ["Batun Bedil"], ["Batun Salak"], ["Batunin"], ["Batunina"], 
        ["Batur"], ["Bau"], ["Baud"], ["Baudanda"], ["Bauh"], ["Baur"], 
        ["Baus"], ["Baut"], ["Bawak"], ["Bawang"], ["Bawi"], ["Bawon"], 
        ["Baya"], ["Baya Kapatut"], ["Bayadan"], ["Bayah"], ["Bayem"], 
        ["Bayingan"], ["Bayu"], ["Bayuh"], ["Bayuhan"], ["Bayune"], 
        ["Bayung"], ["Bayungan"], ["Bayur"], ["Be"], ["Be Balung"], 
        ["Be Guling"], ["Be Tumpek"], ["Be Uyan-uyan"], ["Beb"], ["Bebai"], 
        ["Bebakalan"], ["Bebakuhan"], ["Bebali"], ["Bebaliha"], 
        ["Bebalihan"], ["Bebanci"], ["Bebandungan"], ["Bebangkit"], 
        ["Bebaru"], ["Bebas"], ["Bebataran"], ["Bebaturan"], ["Bebaudan"], 
        ["Bebayan"], ["Bebean"], ["Bebed Sudang"], ["Bebedag"], 
        ["Bebedogan"], ["Bebeg"], ["Bebeh"], ["Bebek"], ["Bebeke"], 
        ["Bebeki"], ["Bebel"], ["Bebenan"], ["Bebencahan"], ["Bebeng"], 
        ["Bebenjulan"], ["Bebesen"], ["Bebet"], ["Bebidakan"], ["Bebinjat"], 
        ["Beblakasan"], ["Beblatukan"], ["Bebokong"], ["Bebolong"], 
        ["Bebonangan"], ["Bebongkasan"], ["Bebontot"], ["Beboreh"], 
        ["Beborehin"], ["Bebotoh"], ["Bebratan"], ["Bebuahan"], 
        ["Bebuduhan"], ["Bebungkilan"], ["Beburon"], ["Becat"], 
        ["Becat-becat"], ["Becatan"], ["Becek"], ["Becica"], ["Becicane"], 
        ["Becik"], ["Becing-becing"], ["Becok"], ["Becol"], ["Becong"], 
        ["Beda"], ["Bedagal"], ["Bedah"], ["Bedak"], ["Bedake"], 
        ["Bedawang"], ["Bedbed"], ["Bedbeda"], ["Bedbedang"], 
        ["Bedbedanga"], ["Bedbedin"], ["Bedbedina"], ["Bede"], ["Bedeg"], 
        ["Bedel"], ["Bedeng"], ["Bedet"], ["Bedigal"], ["Bedik"], 
        ["Bedik-bedik"], ["Bedik-bedikin"], ["Bedikan"], ["Bedil"], 
        ["Bedil-bedilan"], ["Bedog"], ["Bedogol"], ["Bedos"], ["Bedu"], 
        ["Beduda"], ["Bedugul"], ["Bedut"], ["Beduu"], ["Beek"], ["Beenan"], 
        ["Beeng"], ["Begah"], ["Begak"], ["Begal"], ["Begawan"], ["Begbeg"], 
        ["Begeh"], ["Begig"], ["Begina"], ["Begug"], ["Begèr"], ["Beh"], 
        ["Behel"], ["Bejad"], ["Beji"], ["Bejigar"], ["Bejug"], ["Bek"], 
        ["Bekakak"], ["Bekasam"], ["Bekayu"], ["Bekbekan"], ["Bekel"], 
        ["Bekelina"], ["Bekelne"], ["Beki"], ["Bekicot"], ["Bekin"], 
        ["Bekisar"], ["Beku"], ["Bekul"], ["Bekung"], ["Belabar"], 
        ["Belah"], ["Belah-belahan"], ["Belahan"], ["Belang"], 
        ["Belang Belut"], ["Belang Bungkem"], ["Belanjaang"], ["Belas"], 
        ["Belasa"], ["Belasang"], ["Belasanga"], ["Belat"], 
        ["Belatung Gada"], ["Belawa"], ["Belayuran"], ["Beleg"], ["Belek"], 
        ["Belekan"], ["Belekang"], ["Belekanga"], ["Beleng"], ["Beler"], 
        ["Beli"], ["Belianga"], ["Belibar"], ["Belibed"], ["Belibit"], 
        ["Belido"], ["Belig"], ["Belimbing"], ["Belimbing Wuluh"], 
        ["Beling"], ["Belingan"], ["Belitbit"], ["Belog"], 
        ["Belog Magandong"], ["Belong"], ["Belukan"], ["Beluntas"], 
        ["Belur"], ["Belus"], ["Bembangan"], ["Bemo"], ["Ben"], ["Bena"], 
        ["Benahin"], ["Benai"], ["Benal"], ["Benan-benan"], ["Benane"], 
        ["Benang"], ["Benang Pipis"], ["Benang Sedatu"], ["Benang Tridatu"], 
        ["Benangne"], ["Benben"], ["Bencah"], ["Bencangah"], ["Benceng"], 
        ["Bencingah"], ["Bencol"], ["Bende"], ["Bendega"], ["Bendesa"], 
        ["Bendot"], ["Bendu"], ["Bene"], ["Beneh"], ["Benehné"], ["Beneng"], 
        ["Benengan"], ["Beng"], ["Bengah"], ["Bengang"], ["Bengayang"], 
        ["Bengbeng"], ["Bengbenga"], ["Bengek"], ["Bengel"], ["Benges"], 
        ["Bengil"], ["Bengilan"], ["Bengka"], ["Bengkang"], ["Bengkel"], 
        ["Bengking"], ["Bengkis"], ["Bengkoh"], ["Bengkol"], ["Bengkones"], 
        ["Bengkuk"], ["Bengkung"], ["Bengkut"], ["Bengong"], ["Bengor"], 
        ["Bengu"], ["Bengul"], ["Benin"], ["Benjang"], ["Benjang Pungkur"], 
        ["Benjang-benjang"], ["Benjangne"], ["Benjo"], ["Bensin"], 
        ["Bentawas"], ["Bentet"], ["Benting"], ["Bentir"], ["Bentis"], 
        ["Benyad"], ["Benyah"], ["Benyahang"], ["Benyeg"], ["Benyek"], 
        ["Benyel"], ["Benyig"], ["Benyut"], ["Beod"], ["Berag"], 
        ["Berag-beragan"], ["Berang"], ["Berangbang"], ["Beras"], 
        ["Berboga"], ["Bercara"], ["Bered"], ["Berek"], ["Berekan"], 
        ["Berem"], ["Beres"], ["Berig"], ["Beringin"], ["Beris"], ["Berit"], 
        ["Bero"], ["Berong"], ["Beros"], ["Beru"], ["Beruk"], 
        ["Beruk Sileman"], ["Berung"], ["Bes"], ["Besahin"], ["Besakih"], 
        ["Besar"], ["Besbas"], ["Besbes"], ["Beseg"], ["Beseh"], ["Besek"], 
        ["Besen"], ["Beser"], ["Besi"], ["Besi Berani"], ["Besik"], 
        ["Besil"], ["Besus"], ["Bet"], ["Betah"], ["Betak"], ["Betako"], 
        ["Betara"], ["Betara Hyang"], ["Betara-betari"], ["Betarane"], 
        ["Beteg"], ["Betek"], ["Betekan"], ["Betekan Batis"], ["Betel"], 
        ["Beten"], ["Betenan"], ["Beteng"], ["Betet"], ["Betitis"], 
        ["Betok"], ["Beton"], ["Betuk"], ["Betus"], ["Betutu"], ["Beya"], 
        ["Bhagendria"], ["Bhatara"], ["Bhur"], ["Bhuta Yadnya"], ["Biad"], 
        ["Biah-biah"], ["Biakala"], ["Biakta"], ["Biana"], ["Biang"], 
        ["Bianglalah"], ["Biapara"], ["Biar"], ["Bias"], ["Biasa"], 
        ["Biasane"], ["Biat"], ["Biaung"], ["Bibid"], ["Bibih"], ["Bibihe"], 
        ["Bibihne"], ["Bibit"], ["Bibitan"], ["Bicak"], ["Bidag"], ["Bidak"], 
        ["Bidang"], ["Bidara"], ["Bide"], ["Bidugai"], ["Biduri Delima"], 
        ["Biik"], ["Biing"], ["Bija"], ["Bijal"], ["Biji"], ["Bijik"], 
        ["Bikang"], ["Bikas"], ["Biket"], ["Biksuka"], ["Bikul"], 
        ["Bikul Malaibang Pamanggangan"], ["Bikule"], ["Bila"], ["Bilang"], 
        ["Bilangan"], ["Bilih"], ["Bima"], ["Bima Sangara"], ["Bima Krodha"], 
        ["Bimo Kosa"], ["Bina"], ["Binahong"], ["Binal"], ["Binan"], 
        ["Bincuh"], ["Bingar"], ["Bingbang"], ["Bingin"], ["Bingkil"], 
        ["Bingkilan"], ["Bingkit"], ["Bingkrut"], ["Bingung"], ["Bingut"], 
        ["Binih"], ["Bintak"], ["Bintang"], ["Bintang Kudus"], ["Bintaro"], 
        ["Bintenu"], ["Bintil"], ["Bintit"], ["Bintul"], ["Bintulu"], 
        ["Binubuk"], ["Bioskup"], ["Biota"], ["Bir"], ["Biri-biri"], ["Bis"], 
        ["Bisa"], ["Bisaang"], ["Bisain"], ["Bisakan"], ["Bisama"], 
        ["Biseka"], ["Biting"], ["Biu"], ["Biu Batu"], ["Biu Dak"], 
        ["Biu Gadang"], ["Biu Gancan"], ["Biu Gedang Saba"], ["Biu Kat"], 
        ["Biu Kayu Bunga"], ["Biu Ketip"], ["Biu Klopok"], ["Biu Mas"], 
        ["Biu Maselab"], ["Biu Montong"], ["Biu Raja"], ["Biu Sabit"], 
        ["Biu Sawulan"], ["Biu Susu"], ["Biu Udang"], ["Biuh"], ["Biulan"], 
        ["Biunan"], ["Biune"], ["Biur"], ["Bius"], ["Biut"], ["Biyu Kukung"], 
        ["Blabar"], ["Blabaran"], ["Blabor"], ["Blabur"], ["Blacu"], 
        ["Bladbadan"], ["Blaganjur"], ["Blaganjure"], ["Blagbag"], ["Blakas"], 
        ["Blalu"], ["Blanak Kesambi"], ["Blandar"], ["Blandingan"], 
        ["Blang Konyét"], ["Blangko"], ["Blangsah"], ["Blangse"], 
        ["Blangsut"], ["Blanja"], ["Blatuk"], ["Blatung"], ["Blau"], 
        ["Blauk"], ["Blayag"], ["Blayuran"], ["Blebet"], ["Blecek"], 
        ["Blegeran"], ["Blego"], ["Blegos"], ["Blejing"], ["Blekek"], 
        ["Blekok"], ["Blencot"], ["Blendo"], ["Blengbong"], ["Blenget"], 
        ["Blengih"], ["Blengker"], ["Blenguh"], ["Blenyok"], ["Bli"], 
        ["Blibar"], ["Blibis"], ["Bligbagang"], ["Bligo"], ["Bligud"], 
        ["Blikbuk"], ["Blikur"], ["Blimbing"], ["Blimbing Manis"], 
        ["Blingbing"], ["Blinguh"], ["Blitbit"], ["Bliung"], ["Blius"], 
        ["Blodor"], ["Blokotan"], ["Blolong"], ["Blongkak"], ["Blongkang"], 
        ["Blongsong"], ["Blonyoh"], ["Bloran"], ["Bluang"], ["Blubuh"], 
        ["Bludru"], ["Blulang"], ["Bluluk"], ["Blulung"], ["Blungbang"], 
        ["Blungking"], ["Bluntas"], ["Bo"], ["Bobab"], ["Bobok Sajagat"], 
        ["Bobot"], ["Bobotan"], ["Bobotang"], ["Bocok"], ["Bocokan"], 
        ["Bocor"], ["Bodag"], ["Bodo"], ["Bodri"], ["Boga"], ["Bogbog"], 
        ["Bogbogang"], ["Bogbogina"], ["Bogem"], ["Bogol"], ["Bogolan"], 
        ["Boh"], ["Bojog"], ["Bok"], ["Bok Berit"], ["Bok Gelgel"], 
        ["Bok Sosoh"], ["Bokah"], ["Bokan"], ["Bokat"], ["Bokbokina"], 
        ["Boki"], ["Boko"], ["Bokongan"], ["Bokor"], ["Bokoran"], ["Bola"], 
        ["Bolong"], ["Bolos"], ["Bolu"], ["Boma"], ["Bon"], ["Bonan"], 
        ["Boncoh"], ["Boncol"], ["Bondol"], ["Bondres"], ["Boneka"], 
        ["Bongbong"], ["Bonggan"], ["Bongkah"], ["Bongkang"], ["Bongkar"], 
        ["Bongkara"], ["Bongkek"], ["Bongkeng"], ["Bongkok"], ["Bongkol"], 
        ["Bongkol Biu"], ["Bongkolne"], ["Bongkos"], ["Bongkot"], 
        ["Bonglak"], ["Bongoh"], ["Bongok"], ["Bongol"], ["Bongés"], 
        ["Boni"], ["Bonjor"], ["Bonsai"], ["Bontang"], ["Bontok"], 
        ["Bonyok"], ["Bor"], ["Borang"], ["Borboran"], ["Bordir"], ["Boreh"], 
        ["Borgol"], ["Borok"], ["Boros"], ["Boros Wong"], ["Bos"], ["Bosog"], 
        ["Bosok"], ["Botol"], ["Botor"], ["Boya"], ["Boyongan"], ["Bracuk"], 
        ["Bragedegan"], ["Brahma"], ["Brahma Kala"], ["Brahma Kokop"], 
        ["Brahma Labuh Geni"], ["Brahma Padam"], ["Brahma Sandangan"], 
        ["Brahma Sulur"], ["Brahmacari"], ["Brahman"], ["Brahmana"], 
        ["Braja Nembah"], ["Bramara"], ["Brana"], ["Brangasan"], ["Brangbang"], 
        ["Brangkas"], ["Brangti"], ["Brarakina"], ["Brarut"], ["Brasta"], 
        ["Brata"], ["Brawadaan"], ["Brawah"], ["Braya"], ["Brecek"], 
        ["Breco"], ["Brega"], ["Bregah"], ["Bregas"], ["Bregedél"], 
        ["Bregu"], ["Brejog"], ["Brekapat"], ["Brekis"], ["Breng"], 
        ["Brengbeng"], ["Brengkes"], ["Brengos"], ["Breok"], ["Brerong"], 
        ["Bresih"], ["Bresihin"], ["Brigu"], ["Briguna"], ["Bringket"], 
        ["Brokoli"], ["Bronyot"], ["Bros"], ["Brosur"], ["Bruagan"], 
        ["Bruang"], ["Bruit"], ["Brumbun"], ["Brunaha"], ["Brusut"], ["Bua"], 
        ["Buag"], ["Buah"], ["Buah Naga"], ["Buah-buahan"], ["Buaka"], 
        ["Buana"], ["Buang"], ["Buangit"], ["Buat"], ["Buati"], ["Buaya"], 
        ["Buaya Ngangsar"], ["Bubu"], ["Bubug"], ["Bubuh"], ["Bubuh Pirata"], 
        ["Bubuk"], ["Bubul"], ["Bubur Bang"], ["Bucari"], ["Bucu"], ["Buda"], 
        ["Budal"], ["Budalang"], ["Budalanga"], ["Budeg"], ["Budeng"], 
        ["Budi"], ["Budiang"], ["Budianga"], ["Buditama"], ["Buduh"], 
        ["Bugbug"], ["Bui"], ["Buik"], ["Buin"], ["Buin Manine"], 
        ["Buin Ajahan"], ["Buin Akejep"], ["Buina"], ["Buit-buit"], 
        ["Buitan"], ["Buj Angga Amengku"], ["Buj Angga Amerta"], ["Bujangga"], 
        ["Bujuh"], ["Buk"], ["Buka"], ["Bukakak"], ["Bukal"], ["Bukasem"], 
        ["Bukit"], ["Bukit Sakti"], ["Bukti"], ["Buku"], ["Buku-bukune"], 
        ["Bukuan"], ["Bukun"], ["Bukune"], ["Bukur"], ["Bulak-balik"], 
        ["Bulakan"], ["Bulan"], ["Bulan Kerabinan"], ["Bulan Pitung Dina"], 
        ["Bulan Purnama"], ["Bulang"], ["Bule"], ["Buleh"], ["Bulen"], 
        ["Bulenan"], ["Bulene"], ["Bulih"], ["Bulih Sutra"], ["Bulu"],
        ["Buncal"], ["Buncing"], ["Buncul"], ["Bungah"], ["Bungkem"], ["Bungkul"], 
        ["Bungkung"], ["Bungkus"], ["Bunglas"], ["Bungsil"], ["Bungut"], ["Buntar"], 
        ["Buntas"], ["Buntek"], ["Bunter"], ["Buntil"], ["Buntilan"], ["Bunuh"], 
        ["Burik"], ["Buron"], ["Busung"], ["Butuh"], ["Buyar"], ["Buyuk"], 
        ["Buyung"], ["Caak"], ["Cabak"], ["Cabcab"], ["Cabol"], ["Cabul"], 
        ["Cacak"], ["Cacalan"], ["Cacang"], ["Cacar"], ["Cacarang"], ["Cacep"], 
        ["Cadang"], ["Cadel"], ["Cadik"], ["Cadot"], ["Cag-cag"], ["Cagcag"], 
        ["Cager"], ["Caglek"], ["Cagreng"], ["Caguah"], ["Cahcah"], ["Cakal"], 
        ["Cakang"], ["Cakcak"], ["Cakep"], ["Caket"], ["Cakluk"], ["Caku"], 
        ["Cakup"], ["Calcal"], ["Calep"], ["Cali"], ["Caling"], ["Calo"], 
        ["Calon"], ["Caluh"], ["Caluk"], ["Camah"], ["Cambeng"], ["Cambra"], 
        ["Camed"], ["Cameng"], ["Camok"], ["Campah"], ["Campang"], ["Camplung"], 
        ["Campuh"], ["Campur"], ["Camput"], ["Canang"], ["Canda"], ["Candang"], 
        ["Candet"], ["Candik"], ["Canduk"], ["Candung"], ["Caneg"], ["Cangak"], 
        ["Cangcang"], ["Cange"], ["Canggah"], ["Canggem"], ["Cangget"], ["Canggih"], 
        ["Canggol"], ["Canging"], ["Cangkah"], ["Cangkem"], ["Cangkir"], 
        ["Cangkling"], ["Cangklong"], ["Cangklung"], ["Cangkok"], ["Cangkokah"], 
        ["Cangkrama"], ["Cangkrim"], ["Cangkring"], ["Canglak"], ["Cantaka"], 
        ["Canteng"], ["Cantet"], ["Cantik"], ["Canting"], ["Cantok"], ["Capah"], 
        ["Capahan"], ["Capat"], ["Capil"], ["Caping"], ["Caplag"], ["Caplak"], 
        ["Capleng"], ["Caplok"], ["Caplus"], ["Capuh"], ["Capung"], ["Cara"], 
        ["Carak"], ["Caraka"], ["Carakan"], ["Carang"], ["Caratan"], ["Carca"], 
        ["Carcan"], ["Carik"], ["Caritan"], ["Caru"], ["Carub"], ["Caruk"], 
        ["Catet"], ["Catok"], ["Catra"], ["Catri"], ["Catu"], ["Catur"], 
        ["Catut"], ["Cawan"], ["Cawang"], ["Cawet"], ["Caya"], ["Cebleng"], 
        ["Cebur"], ["Cecak"], ["Cecapan"], ["Cecek"], ["Cecel"], ["Cecetrung"], 
        ["Cecimpedan"], ["Cecunduk"], ["Ceda"], ["Cedang"], ["Cedar"], ["Cedik"], 
        ["Cedil"], ["Cedok"], ["Cedor"], ["Ceeng"], ["Cegah"], ["Cegceg"], 
        ["Cegem"], ["Cegeng"], ["Ceget"], ["Ceglong"], ["Cegur"], ["Cegut"], 
        ["Cekak"], ["Cekcek"], ["Cekel"], ["Cekepit"], ["Cekian"], ["Ceking"], 
        ["Cekok"], ["Cekot"], ["Cekuh"], ["Cekuk"], ["Celagi"], ["Celak"], 
        ["Celana"], ["Celang"], ["Celcel"], ["Celeb"], ["Celebingkah"], ["Celebo"], 
        ["Celed"], ["Celeda"], ["Celedu"], ["Celek"], ["Celekang"], ["Celekutan"], 
        ["Celekutukan"], ["Celembu"], ["Celemik"], ["Celeng"], ["Celengan"], 
        ["Celengang"], ["Celengin"], ["Celep"], ["Celepang"], ["Celepin"], 
        ["Celepuk"], ["Celig"], ["Celih"], ["Celing"], ["Celocoh"], ["Celong"], 
        ["Celor"], ["Celuk"], ["Celuluk"], ["Celut"], ["Cemara"], ["Cematu"], 
        ["Cemburu"], ["Cemcem"], ["Cemeng"], ["Cemer"], ["Cemil"], ["Cemoh"], 
        ["Cempaka"], ["Cempaluk"], ["Cemped"], ["Cempedan"], ["Cemplung"], 
        ["Cempurit"], ["Cemung"], ["Cendek"], ["Cendet"], ["Cendol"], ["Ceng"], 
        ["Cengceng"], ["Cengeg"], ["Cengelan"], ["Cengkang"], ["Cengkeh"], 
        ["Cengkilik"], ["Cengkirian"], ["Cengklik"], ["Cengkok"], ["Cengkrong"], 
        ["Cengkud"], ["Cengong"], ["Cengurit"], ["Cenidra"], ["Ceniga"], 
        ["Cenik"], ["Cenikih"], ["Cenil"], ["Cening"], ["Centong"], ["Centula"], 
        ["Cepag"], ["Cepaka"], ["Cepedin"], ["Cepek"], ["Ceper"], ["Cepet"], 
        ["Cepikan"], ["Cepil"], ["Ceping"], ["Ceplag"], ["Cepok"], ["Cepokang"], 
        ["Cepol"], ["Cepong"], ["Cepuk"], ["Cepung"], ["Cera"], ["Ceracap"], 
        ["Cerah"], ["Cerai"], ["Ceraken"], ["Ceraki"], ["Cerancam"], ["Ceregan"], 
        ["Cerekcek"], ["Cerekuak"], ["Cerekuwak"], ["Cereme"], ["Cererek"], 
        ["Ceret"], ["Cerida"], ["Cerik"], ["Ceriritan"], ["Cerita"], ["Cerme"], 
        ["Cermin"], ["Cero"], ["Cerobo"], ["Cerok"], ["Cerongcong"], ["Ceroring"], 
        ["Cerorit"], ["Cerorot"], ["Cerucut"], ["Cerukcuk"], ["Cet"], ["Cetak"], 
        ["Cetana"], ["Ceteng"], ["Cetet"], ["Cetik"], ["Cetok"], ["Cibluk"], 
        ["Cicak"], ["Cicih"], ["Cicilan"], ["Cicing"], ["Cicip"], ["Cicipin"], 
        ["Cidra"], ["Cihna"], ["Cihnain"], ["Cihnayang"], ["Ciing"], ["Ciit"], 
        ["Cik"], ["Cikal"], ["Cikar"], ["Cikut"], ["Cilak"], ["Cili"], ["Cina"], 
        ["Cincin"], ["Cindana"], ["Cingak"], ["Cingakin"], ["Cinggur"], 
        ["Cinging"], ["Cingkrem"], ["Cinglar"], ["Cintamani"], ["Cipak"], 
        ["Ciplakan"], ["Cipta Kukila"], ["Ciri"], ["Citakan"], ["Citrakara"], 
        ["Ciung"], ["Clagi"], ["Clalongan"], ["Clana"], ["Clebongkak"], ["Cledced"], 
        ["Clegokan"], ["Clekutan"], ["Clemik"], ["Clengagan"], ["Clengis"], 
        ["Clepuk"], ["Clika"], ["Clodoh"], ["Clucuh"], ["Clurit"], ["Coak"], 
        ["Coba"], ["Cobek"], ["Coblak"], ["Coblok"], ["Coblong"], ["Cocoh"], 
        ["Cocok"], ["Cocol"], ["Cocolan"], ["Cocong"], ["Cocor"], ["Codet"], 
        ["Cogroh"], ["Cok"], ["Cokcok"], ["Cokeh"], ["Cokeli"], ["Coklat"], 
        ["Cokok"], ["Cokor"], ["Cokot"], ["Colek"], ["Colo"], ["Coloh"], ["Colok"], 
        ["Colong"], ["Coma"], ["Comel"], ["Compeng"], ["Compong"], ["Condong"], 
        ["Congah"], ["Congcong"], ["Congeh"], ["Congkak"], ["Congkeh"], 
        ["Congklok"], ["Congkod"], ["Cono"], ["Conto"], ["Contok"], ["Contreng"], 
        ["Coong"], ["Copah"], ["Copet"], ["Coples"], ["Cor"], ["Corah"], 
        ["Corahan"], ["Corak"], ["Corcor"], ["Corek"], ["Corong"], ["Cote"], 
        ["Cotek"], ["Cotol"], ["Coton"], ["Cracah"], ["Cracapan"], ["Craki"], 
        ["Cramah"], ["Cramcam"], ["Crawis"], ["Creceh"], ["Crekcek"], ["Creki"], 
        ["Creme"], ["Cremi"], ["Crenggah"], ["Creretin"], ["Crewet"], ["Criritan"], 
        ["Crita"], ["Crobo"], ["Crongcong"], ["Croring"], ["Crorot"], ["Cruing"], 
        ["Crukcuk"], ["Cub"], ["Cubang"], ["Cublik"], ["Cubluk"], ["Cucu"], 
        ["Cucud"], ["Cucuk"], ["Cueng"], ["Cuet"], ["Cuil"], ["Cuk"], ["Cukcuk"], 
        ["Cuken"], ["Cuki"], ["Cukit"], ["Cukur"], ["Cula"], ["Culalong"], 
        ["Culig"], ["Culing"], ["Culuung"], ["Cumbuana"], ["Cumpu"], ["Cundang"], 
        ["Cunding"], ["Cunduk"], ["Cungih"], ["Cungklik"], ["Cunguh"], ["Cuntaka"], 
        ["Cupak"], ["Cupar"], ["Cupek"], ["Cupik"], ["Cupit"], ["Cupu"], ["Curek"], 
        ["Curiga"], ["Curik"], ["Curing"], ["Curna"], ["Cutet"], ["Cyuta"], 
        ["Daar"], ["Daat"], ["Dabdab"], ["Dacin"], ["Dada"], ["Dadaaran"], 
        ["Dadag"], ["Dadah"], ["Dadak"], ["Dadalan"], ["Dadalu"], ["Dadaluman"], 
        ["Dadang"], ["Dadap"], ["Dadar"], ["Dadata"], ["Dadawuhan"], ["Dadi"], 
        ["Dadia"], ["Dadiang"], ["Dadinan"], ["Dadong"], ["Dados"], ["Dadosang"], 
        ["Dadu"], ["Dadua"], ["Dadung"], ["Daem"], ["Dag"], ["Daga"], ["Dagad"], 
        ["Dagang"], ["Dagdag"], ["Dagel"], ["Daging"], ["Dagingin"], ["Daha"], 
        ["Dahat"], ["Daja"], ["Dakangan"], ["Daken"], ["Dakep"], ["Dakepa"], 
        ["Dakepang"], ["Dakepanga"], ["Daki"], ["Dakit"], ["Daksa"], ["Daksina"], 
        ["Dalancang"], ["Dalang"], ["Dalem"], ["Daleman"], ["Dalet"], ["Dalih"], 
        ["Dalil"], ["Dalit"], ["Dalu"], ["Daluman"], ["Dama"], ["Damah"], 
        ["Damala"], ["Damang"], ["Damar"], ["Dame"], ["Damel"], ["Dami"], 
        ["Damil"], ["Dampar"], ["Dampeh"], ["Damper"], ["Damping"], ["Dampingin"], 
        ["Damprat"], ["Dampuk"], ["Dampukan"], ["Damuh"], ["Dana"], ["Danan"], 
        ["Danarasa"], ["Danawa"], ["Danda"], ["Dandan"], ["Dang"], ["Dangan"], 
        ["Danganan"], ["Dangdang"], ["Dangdung"], ["Danggul"], ["Dangil"], 
        ["Dangin"], ["Dangkal"], ["Dangkangan"], ["Dangla"], ["Dangsah"], 
        ["Dangsahang"], ["Dangsahanga"], ["Dangsek"], ["Dangsil"], ["Dangu"], 
        ["Dangul"], ["Danta"], ["Danu"], ["Danuja"], ["Danyuh"], ["Dapak"], 
        ["Dapang"], ["Dapdap Tis"], ["Dapdapangan"], ["Dapes"], ["Dapet"], 
        ["Dapetan"], ["Dapetanga"], ["Daptar"], ["Dapur"], ["Dara"], ["Darane"], 
        ["Daridra"], ["Darma"], ["Darpana"], ["Darsana"], ["Das"], ["Dasa"], 
        ["Dasan"], ["Dasar"], ["Dasaran"], ["Dasari"], ["Dasi"], ["Daslemah"], 
        ["Datengan"], ["Datu"], ["Dauhan"], ["Dauhang"], ["Dausa"], ["Dausa Gede"], 
        ["Dausa Keling"], ["Daut"], ["Dawa"], ["Dawane"], ["Dawat"], ["Daweg"], 
        ["Dawet"], ["Dawuk"], ["Daya"], ["Dayane"], ["Dayang-dayang"], 
        ["Dayanin"], ["Dayu"], ["Dayuh"], ["Dayung"], ["Debat"], ["Dedaaran"], 
        ["Dedaletan"], ["Dedali"], ["Dedampar"], ["Dedamping"], ["Dedanga"], 
        ["Dedap"], ["Dedari"], ["Dedauhan"], ["Dedeh"], ["Dedel"], ["Dedemenan"], 
        ["Dedet"], ["Dedosan"], ["Dedudukan"], ["Dedungkian"], ["Deeng"], 
        ["Degag"], ["Degdeg"], ["Degdegan"], ["Degeng"], ["Deha"], ["Dek"], 
        ["Dekah"], ["Dekdek"], ["Dekdekan"], ["Dekem"], ["Dekes"], ["Deket"], 
        ["Dekil"], ["Dekorasi"], ["Dekung"], ["Dekungan"], ["Del"], ["Deldel"], 
        ["Deldela"], ["Deldelang"], ["Deldelanga"], ["Deleg"], ["Delek"], 
        ["Delem"], ["Delep"], ["Delik"], ["Delima"], ["Deling"], ["Delman"], 
        ["Delod"], ["Delokin"], ["Deluang"], ["Deluh"], ["Delundung"], ["Demang"], 
        ["Dembel"], ["Demdem"], ["Demek"], ["Demem"], ["Demen"], ["Demenan"], 
        ["Demenin"], ["Demerit"], ["Demih"], ["Demit"]
    ],

    "Prep": [
         ["Antuk"], ["Bareng"], ["Barengan"], ["Bareng-bareng"], ["Base"], ["Base Temisi"], 
        ["Base Tulak"], ["Biang"], ["Biang-biang"], ["Bianglalah"], ["Bias"], 
        ["Biasa"], ["Biasane"], ["Biat"], ["Biaung"], ["Bibid"], ["Bibih"], 
        ["Bibihne"], ["Bibit"], ["Bibitan"], ["Bicak"], ["Bidag"], ["Bidak"], 
        ["Bidang"], ["Bidara"], ["Bide"], ["Bidugai"], ["Biduri Delima"], 
        ["Biik"], ["Biing"], ["Bija"], ["Bijal"], ["Biji"], ["Bijik"], 
        ["Bikang"], ["Bikas"], ["Biket"], ["Biksuka"], ["Bikul"], 
        ["Bikul Malaibang Pamanggangan"], ["Bikule"], ["Bila"], ["Bilang"], 
        ["Bilangan"], ["Bilih"], ["Bima"], ["Bima Sangara"], ["Bima Krodha"], 
        ["Bimo Kosa"], ["Bina"], ["Binahong"], ["Binal"], ["Binan"], 
        ["Bincuh"], ["Bingar"], ["Bingbang"], ["Bingin"], ["Bingkil"], 
        ["Bingkilan"], ["Bingkit"], ["Bingkrut"], ["Bingung"], ["Bingut"], 
        ["Binih"], ["Bintak"], ["Bintang"], ["Bintang Kudus"], ["Bintaro"], 
        ["Bintenu"], ["Bintil"], ["Bintit"], ["Bintul"], ["Bintulu"], 
        ["Binubuk"], ["Bioskup"], ["Biota"], ["Bir"], ["Biri-biri"], ["Bis"], 
        ["Bisa"], ["Bisaang"], ["Bisain"], ["Bisakan"], ["Bisama"], 
        ["Biseka"], ["Biting"], ["Biu"], ["Biu Batu"], ["Biu Dak"], 
        ["Biu Gadang"], ["Biu Gancan"], ["Biu Gedang Saba"], ["Biu Kat"], 
        ["Biu Kayu Bunga"], ["Biu Ketip"], ["Biu Klopok"], ["Biu Mas"], 
        ["Biu Maselab"], ["Biu Montong"], ["Biu Raja"], ["Biu Sabit"], 
        ["Biu Sawulan"], ["Biu Susu"], ["Biu Udang"], ["Biuh"], ["Biulan"], 
        ["Biunan"], ["Biune"], ["Biur"], ["Bius"], ["Biut"], ["Biyu Kukung"], 
        ["Blabar"], ["Blabaran"], ["Blabor"], ["Blabur"], ["Blacu"], 
        ["Bladbadan"], ["Blaganjur"], ["Blaganjure"], ["Blagbag"], ["Blakas"], 
        ["Blalu"], ["Blanak Kesambi"], ["Blandar"], ["Blandingan"], 
        ["Blang Konyét"], ["Blangko"], ["Blangsah"], ["Blangse"], 
        ["Blangsut"], ["Blanja"], ["Blatuk"], ["Blatung"], ["Blau"], 
        ["Blauk"], ["Blayag"], ["Blayuran"], ["Blebet"], ["Blecek"], 
        ["Blegeran"], ["Blego"], ["Blegos"], ["Blejing"], ["Blekek"], 
        ["Blekok"], ["Blencot"], ["Blendo"], ["Blengbong"], ["Blenget"], 
        ["Blengih"], ["Blengker"], ["Blenguh"], ["Blenyok"], ["Bli"], 
        ["Blibar"], ["Blibis"], ["Bligbagang"], ["Bligo"], ["Bligud"], 
        ["Blikbuk"], ["Blikur"], ["Blimbing"], ["Blimbing Manis"], 
        ["Blingbing"], ["Blinguh"], ["Blitbit"], ["Bliung"], ["Blius"], 
        ["Blodor"], ["Blokotan"], ["Blolong"], ["Blongkak"], ["Blongkang"], 
        ["Blongsong"], ["Blonyoh"], ["Bloran"], ["Bluang"], ["Blubuh"], 
        ["Bludru"], ["Blulang"], ["Bluluk"], ["Blulung"], ["Blungbang"], 
        ["Blungking"], ["Bluntas"], ["Bo"], ["Bobab"], ["Bobok Sajagat"], 
        ["Bobot"], ["Bobotan"], ["Bobotang"], ["Bocok"], ["Bocokan"], 
        ["Bocor"], ["Bodag"], ["Bodo"], ["Bodri"], ["Boga"], ["Bogbog"], 
        ["Bogbogang"], ["Bogbogina"], ["Bogem"], ["Bogol"], ["Bogolan"], 
        ["Boh"], ["Bojog"], ["Bok"], ["Bok Berit"], ["Bok Gelgel"], 
        ["Bok Sosoh"], ["Bokah"], ["Bokan"], ["Bokat"], ["Bokbokina"], 
        ["Boki"], ["Boko"], ["Bokongan"], ["Bokor"], ["Bokoran"], ["Bola"], 
        ["Bolong"], ["Bolos"], ["Bolu"], ["Boma"], ["Bon"], ["Bonan"], 
        ["Boncoh"], ["Boncol"], ["Bondol"], ["Bondres"], ["Boneka"], 
        ["Bongbong"], ["Bonggan"], ["Bongkah"], ["Bongkang"], ["Bongkar"], 
        ["Bongkara"], ["Bongkek"], ["Bongkeng"], ["Bongkok"], ["Bongkol"], 
        ["Bongkol Biu"], ["Bongkolne"], ["Bongkos"], ["Bongkot"], 
        ["Bonglak"], ["Bongoh"], ["Bongok"], ["Bongol"], ["Bongés"], 
        ["Boni"], ["Bonjor"], ["Bonsai"], ["Bontang"], ["Bontok"], 
        ["Bonyok"], ["Bor"], ["Borang"], ["Borboran"], ["Bordir"], ["Boreh"], 
        ["Borgol"], ["Borok"], ["Boros"], ["Boros Wong"], ["Bos"], ["Bosog"], 
        ["Bosok"], ["Botol"], ["Botor"], ["Boya"], ["Boyongan"], ["Bracuk"], 
        ["Bragedegan"], ["Brahma"], ["Brahma Kala"], ["Brahma Kokop"], 
        ["Brahma Labuh Geni"], ["Brahma Padam"], ["Brahma Sandangan"], 
        ["Brahma Sulur"], ["Brahmacari"], ["Brahman"], ["Brahmana"], 
        ["Braja Nembah"], ["Bramara"], ["Brana"], ["Brangasan"], ["Brangbang"], 
        ["Brangkas"], ["Brangti"], ["Brarakina"], ["Brarut"], ["Brasta"], 
        ["Brata"], ["Brawadaan"], ["Brawah"], ["Braya"], ["Brecek"], 
        ["Breco"], ["Brega"], ["Bregah"], ["Bregas"], ["Bregedél"], 
        ["Bregu"], ["Brejog"], ["Brekapat"], ["Brekis"], ["Breng"], 
        ["Brengbeng"], ["Brengkes"], ["Brengos"], ["Breok"], ["Brerong"], 
        ["Bresih"], ["Bresihin"], ["Brigu"], ["Briguna"], ["Bringket"], 
        ["Brokoli"], ["Bronyot"], ["Bros"], ["Brosur"], ["Bruagan"], 
        ["Bruang"], ["Bruit"], ["Brumbun"], ["Brunaha"], ["Brusut"], ["Bua"], 
        ["Buag"], ["Buah"], ["Buah Naga"], ["Buah-buahan"], ["Buaka"], 
        ["Buana"], ["Buang"], ["Buangit"], ["Buat"], ["Buati"], ["Buaya"], 
        ["Buaya Ngangsar"], ["Bubu"], ["Bubug"], ["Bubuh"], ["Bubuh Pirata"], 
        ["Bubuk"], ["Bubul"], ["Bubur Bang"], ["Bucari"], ["Bucu"], ["Buda"], 
        ["Budal"], ["Budalang"], ["Budalanga"], ["Budeg"], ["Budeng"], 
        ["Budi"], ["Budiang"], ["Budianga"], ["Buditama"], ["Buduh"], 
        ["Bugbug"], ["Bui"], ["Buik"], ["Buin"], ["Buin Manine"], 
        ["Buin Ajahan"], ["Buin Akejep"], ["Buina"], ["Buit-buit"], 
        ["Buitan"], ["Buj Angga Amengku"], ["Buj Angga Amerta"], ["Bujangga"], 
        ["Bujuh"], ["Buk"], ["Buka"], ["Bukakak"], ["Bukal"], ["Bukasem"], 
        ["Bukit"], ["Bukit Sakti"], ["Bukti"], ["Buku"], ["Buku-bukune"], 
        ["Bukuan"], ["Bukun"], ["Bukune"], ["Bukur"], ["Bulak-balik"], 
        ["Bulakan"], ["Bulan"], ["Bulan Kerabinan"], ["Bulan Pitung Dina"], 
        ["Bulan Purnama"], ["Bulang"], ["Bule"], ["Buleh"], ["Bulen"], 
        ["Bulenan"], ["Bulene"], ["Bulih"], ["Bulih Sutra"], ["Bulu"],
        ["Da"], ["Dane"], ["Dangin"], ["Dari"], ["Dau"], ["Delod"], ["Demit"]
    ]
}
